# Generated by Django 6.0.6 on 2026-08-21 13:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("integration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Metadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Identifier of the metadata.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The verbose title of the connected item.",
                        max_length=1000,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "license",
                    models.TextField(
                        default="\n    This dataset is made available under the Open Database\n    License: http://opendatacommons.org/licenses/odbl/1.0/.\n    Any rights in individual contents of the database are licensed\n    under the Database Contents\n    License: http://opendatacommons.org/licenses/dbcl/1.0/\n    "
                    ),
                ),
                ("fees", models.TextField(default="No fees apply.")),
                (
                    "access_constraints",
                    models.TextField(default="No access constraints apply."),
                ),
            ],
            options={
                "verbose_name": "metadata",
                "verbose_name_plural": "metadata",
            },
        ),
        migrations.CreateModel(
            name="UrlShortener",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
                ("url", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("public", models.BooleanField(default=False)),
                ("ordering", models.IntegerField()),
                ("location", models.JSONField(null=True)),
                ("zoom", models.IntegerField(null=True)),
                ("theme_json", models.JSONField()),
                (
                    "metadata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="themes",
                        to="webgis.metadata",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="themes",
                        to="integration.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
                "ordering": ["ordering"],
                "permissions": [
                    ("manage_object_permissions", "Can manage object permissions"),
                    ("view_published_theme", "Can view published theme"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WmsLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Identifier of the wms layer.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("public", models.BooleanField(default=False)),
                (
                    "extent_buffer",
                    models.FloatField(
                        default=0.0, help_text="Extent buffer size of the layer"
                    ),
                ),
                (
                    "queryable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether GetFeature requests are allowed on this layer.",
                    ),
                ),
                (
                    "extent",
                    models.CharField(
                        blank=True,
                        help_text="Extent of the layer in its stored CRS.",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "extent_wgs84",
                    models.CharField(
                        blank=True,
                        help_text="Extent of the layer in WGS84 CRS.",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "preview",
                    models.BinaryField(
                        blank=True, help_text="Preview image of the layer.", null=True
                    ),
                ),
                (
                    "min_resolution_hint",
                    models.FloatField(
                        default=0.0,
                        help_text="Below this resolution the layer won't be drawn.",
                    ),
                ),
                (
                    "max_resolution_hint",
                    models.FloatField(
                        default=999999999.0,
                        help_text="Above this scale the layer won't be drawn.",
                    ),
                ),
                (
                    "datasource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webgis_wms_layers",
                        to="integration.datasource",
                    ),
                ),
                (
                    "metadata",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webgis_wms_layers",
                        to="webgis.metadata",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wms_layers",
                        to="webgis.theme",
                    ),
                ),
            ],
            options={
                "verbose_name": "WMS Layer",
                "verbose_name_plural": "WMS Layers",
                "permissions": [("view_published_layer", "Can view published layer")],
            },
        ),
        migrations.CreateModel(
            name="ThemeGroupObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_object_permissions",
                        to="webgis.theme",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("group", "permission", "content_object")},
            },
        ),
        migrations.CreateModel(
            name="ThemeUserObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_object_permissions",
                        to="webgis.theme",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("user", "permission", "content_object")},
            },
        ),
    ]
