# Generated by Django 5.0.6 on 2024-12-11 14:49

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data_integration", "0020_remove_vectordataset_extent_buffer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField()),
                ("description", models.CharField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Interface",
                "verbose_name_plural": "Interfaces",
            },
        ),
        migrations.CreateModel(
            name="LayerGroupMp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("themes_json_id", models.IntegerField(null=True)),
                ("name", models.CharField(max_length=128)),
                ("metadata", models.JSONField(default=None, null=True)),
                ("mixed", models.BooleanField(default=None, null=True)),
                ("ogc_server", models.CharField(default=None, max_length=2048, null=True)),
                ("dimensions", models.JSONField(default=None, null=True)),
            ],
            options={
                "verbose_name": "Groupe de de couche",
                "verbose_name_plural": "Groupes de couche",
            },
        ),
        migrations.CreateModel(
            name="HistoricalInterface",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField()),
                ("description", models.CharField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Interface",
                "verbose_name_plural": "historical Interfaces",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOgcServer",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField()),
                ("type", models.CharField()),
                ("credential", models.BooleanField(default=False)),
                ("image_type", models.CharField()),
                ("wfs_support", models.BooleanField(blank=True, null=True)),
                ("is_single_tile", models.BooleanField(blank=True, null=True)),
                ("namespace", models.CharField(null=True)),
                ("name", models.CharField(null=True)),
                ("description", models.CharField(blank=True, null=True)),
                ("url_wfs", models.URLField(blank=True, null=True)),
                ("attributes", models.JSONField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mandant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="ogc_server",
                        to="data_integration.mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Serveur OGC",
                "verbose_name_plural": "historical Serveurs OGC",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPublishedAsTheme",
            fields=[
                (
                    "identifier",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "name",
                    models.CharField(blank=True, default=None, max_length=1000, null=True),
                ),
                ("public", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(blank=True, default=None, max_length=1000, null=True),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "license",
                    models.TextField(
                        default="\n    This dataset is made available under the Open Database\n    License: http://opendatacommons.org/licenses/odbl/1.0/.\n    Any rights in individual contents of the database are licensed\n    under the Database Contents\n    License: http://opendatacommons.org/licenses/dbcl/1.0/\n    "
                    ),
                ),
                ("fees", models.TextField(default="No fees apply.")),
                (
                    "access_constraints",
                    models.TextField(default="No access constraints apply."),
                ),
                ("themes_json_id", models.IntegerField(null=True)),
                ("metadata", models.JSONField()),
                ("icon", models.CharField(blank=True, null=True)),
                ("ordering", models.IntegerField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="published_as_geogirafe_theme",
                        to="data_integration.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Thème",
                "verbose_name_plural": "historical Thèmes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPublishedAsLayerWmts",
            fields=[
                (
                    "identifier",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "name",
                    models.CharField(blank=True, default=None, max_length=1000, null=True),
                ),
                ("public", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(blank=True, default=None, max_length=1000, null=True),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "license",
                    models.TextField(
                        default="\n    This dataset is made available under the Open Database\n    License: http://opendatacommons.org/licenses/odbl/1.0/.\n    Any rights in individual contents of the database are licensed\n    under the Database Contents\n    License: http://opendatacommons.org/licenses/dbcl/1.0/\n    "
                    ),
                ),
                ("fees", models.TextField(default="No fees apply.")),
                (
                    "access_constraints",
                    models.TextField(default="No access constraints apply."),
                ),
                ("themes_json_id", models.IntegerField(null=True)),
                ("metadata", models.JSONField(default=None, null=True)),
                ("dimensions", models.JSONField(default=None, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="published_as_geogirafe_wmts",
                        to="data_integration.rasterdataset",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "layer_group",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="wmts_dataset",
                        to="webgis.layergroupmp",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical WMTS Layer",
                "verbose_name_plural": "historical WMTS Layers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPublishedAsLayerWms",
            fields=[
                (
                    "identifier",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "name",
                    models.CharField(blank=True, default=None, max_length=1000, null=True),
                ),
                ("public", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(blank=True, default=None, max_length=1000, null=True),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "license",
                    models.TextField(
                        default="\n    This dataset is made available under the Open Database\n    License: http://opendatacommons.org/licenses/odbl/1.0/.\n    Any rights in individual contents of the database are licensed\n    under the Database Contents\n    License: http://opendatacommons.org/licenses/dbcl/1.0/\n    "
                    ),
                ),
                ("fees", models.TextField(default="No fees apply.")),
                (
                    "access_constraints",
                    models.TextField(default="No access constraints apply."),
                ),
                ("themes_json_id", models.IntegerField(null=True)),
                ("metadata", models.JSONField(default=None, null=True)),
                ("dimensions", models.JSONField(default=None, null=True)),
                ("ogc_server", models.CharField(null=True)),
                ("min_resolution_hint", models.FloatField(default=None)),
                ("max_resolution_hint", models.FloatField(default=None)),
                ("child_layers", models.JSONField(default=None)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="published_as_geogirafe_wms",
                        to="data_integration.rasterdataset",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "layer_group",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="wms_dataset",
                        to="webgis.layergroupmp",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Couche WMS",
                "verbose_name_plural": "historical Couches WMS",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OgcServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField()),
                ("type", models.CharField()),
                ("credential", models.BooleanField(default=False)),
                ("image_type", models.CharField()),
                ("wfs_support", models.BooleanField(blank=True, null=True)),
                ("is_single_tile", models.BooleanField(blank=True, null=True)),
                ("namespace", models.CharField(null=True)),
                ("name", models.CharField(null=True)),
                ("description", models.CharField(blank=True, null=True)),
                ("url_wfs", models.URLField(blank=True, null=True)),
                ("attributes", models.JSONField(blank=True, null=True)),
                (
                    "mandant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ogc_servers",
                        related_query_name="ogc_server",
                        to="data_integration.mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serveur OGC",
                "verbose_name_plural": "Serveurs OGC",
            },
        ),
        migrations.CreateModel(
            name="PublishedAsLayerWms",
            fields=[
                (
                    "identifier",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default=None, max_length=1000, null=True),
                ),
                ("public", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(blank=True, default=None, max_length=1000, null=True),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "license",
                    models.TextField(
                        default="\n    This dataset is made available under the Open Database\n    License: http://opendatacommons.org/licenses/odbl/1.0/.\n    Any rights in individual contents of the database are licensed\n    under the Database Contents\n    License: http://opendatacommons.org/licenses/dbcl/1.0/\n    "
                    ),
                ),
                ("fees", models.TextField(default="No fees apply.")),
                (
                    "access_constraints",
                    models.TextField(default="No access constraints apply."),
                ),
                ("themes_json_id", models.IntegerField(null=True)),
                ("metadata", models.JSONField(default=None, null=True)),
                ("dimensions", models.JSONField(default=None, null=True)),
                ("ogc_server", models.CharField(null=True)),
                ("min_resolution_hint", models.FloatField(default=None)),
                ("max_resolution_hint", models.FloatField(default=None)),
                ("child_layers", models.JSONField(default=None)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_as_geogirafe_wmss",
                        related_query_name="published_as_geogirafe_wms",
                        to="data_integration.rasterdataset",
                    ),
                ),
                (
                    "layer_group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wms_datasets",
                        related_query_name="wms_dataset",
                        to="webgis.layergroupmp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Couche WMS",
                "verbose_name_plural": "Couches WMS",
            },
        ),
        migrations.CreateModel(
            name="PublishedAsLayerWmts",
            fields=[
                (
                    "identifier",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default=None, max_length=1000, null=True),
                ),
                ("public", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(blank=True, default=None, max_length=1000, null=True),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "license",
                    models.TextField(
                        default="\n    This dataset is made available under the Open Database\n    License: http://opendatacommons.org/licenses/odbl/1.0/.\n    Any rights in individual contents of the database are licensed\n    under the Database Contents\n    License: http://opendatacommons.org/licenses/dbcl/1.0/\n    "
                    ),
                ),
                ("fees", models.TextField(default="No fees apply.")),
                (
                    "access_constraints",
                    models.TextField(default="No access constraints apply."),
                ),
                ("themes_json_id", models.IntegerField(null=True)),
                ("metadata", models.JSONField(default=None, null=True)),
                ("dimensions", models.JSONField(default=None, null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_as_geogirafe_wmtss",
                        related_query_name="published_as_geogirafe_wmts",
                        to="data_integration.rasterdataset",
                    ),
                ),
                (
                    "layer_group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wmts_datasets",
                        related_query_name="wmts_dataset",
                        to="webgis.layergroupmp",
                    ),
                ),
            ],
            options={
                "verbose_name": "WMTS Layer",
                "verbose_name_plural": "WMTS Layers",
            },
        ),
        migrations.CreateModel(
            name="PublishedAsTheme",
            fields=[
                (
                    "identifier",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default=None, max_length=1000, null=True),
                ),
                ("public", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(blank=True, default=None, max_length=1000, null=True),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "license",
                    models.TextField(
                        default="\n    This dataset is made available under the Open Database\n    License: http://opendatacommons.org/licenses/odbl/1.0/.\n    Any rights in individual contents of the database are licensed\n    under the Database Contents\n    License: http://opendatacommons.org/licenses/dbcl/1.0/\n    "
                    ),
                ),
                ("fees", models.TextField(default="No fees apply.")),
                (
                    "access_constraints",
                    models.TextField(default="No access constraints apply."),
                ),
                ("themes_json_id", models.IntegerField(null=True)),
                ("metadata", models.JSONField()),
                ("icon", models.CharField(blank=True, null=True)),
                ("ordering", models.IntegerField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_as_geogirafe_themes",
                        related_query_name="published_as_geogirafe_theme",
                        to="data_integration.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thème",
                "verbose_name_plural": "Thèmes",
                "ordering": ["ordering"],
            },
        ),
        migrations.AddField(
            model_name="layergroupmp",
            name="theme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tree_elements",
                related_query_name="tree_element",
                to="webgis.publishedastheme",
            ),
        ),
    ]
