# Generated by Django 5.0.6 on 2025-05-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webgis", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalogcserver",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalogcserver",
            name="mandant",
        ),
        migrations.RemoveField(
            model_name="historicalpublishedaslayerwms",
            name="dataset",
        ),
        migrations.RemoveField(
            model_name="historicalpublishedaslayerwms",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalpublishedaslayerwms",
            name="layer_group",
        ),
        migrations.RemoveField(
            model_name="historicalpublishedaslayerwmts",
            name="dataset",
        ),
        migrations.RemoveField(
            model_name="historicalpublishedaslayerwmts",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalpublishedaslayerwmts",
            name="layer_group",
        ),
        migrations.RemoveField(
            model_name="historicalpublishedastheme",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalpublishedastheme",
            name="project",
        ),
        migrations.DeleteModel(
            name="HistoricalInterface",
        ),
        migrations.DeleteModel(
            name="HistoricalOgcServer",
        ),
        migrations.DeleteModel(
            name="HistoricalPublishedAsLayerWms",
        ),
        migrations.DeleteModel(
            name="HistoricalPublishedAsLayerWmts",
        ),
        migrations.DeleteModel(
            name="HistoricalPublishedAsTheme",
        ),
    ]
