# Generated by Django 6.0.6 on 2026-09-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='background_layers',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
