# Generated by Django 6.0.6 on 2026-09-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0002_theme_background_layers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='location',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='zoom',
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_layers',
            field=models.JSONField(blank=True),
        ),
    ]
