# Generated by Django 6.0.6 on 2026-09-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0003_remove_theme_location_remove_theme_zoom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wmslayer',
            name='public',
        ),
    ]
