# Generated by Django 5.0.6 on 2025-05-29 14:14

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webgis", "0003_remove_publishedaslayerwms_dataset_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publishedaslayerwms",
            name="themes_json_id",
        ),
        migrations.RemoveField(
            model_name="publishedaslayerwmts",
            name="themes_json_id",
        ),
        migrations.AddField(
            model_name="publishedaslayerwms",
            name="themes_json_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="publishedaslayerwmts",
            name="themes_json_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
