# Generated by Django 5.0.6 on 2025-05-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webgis", "0004_remove_publishedaslayerwms_themes_json_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="layergroupmp",
            options={"verbose_name": "Layer Group", "verbose_name_plural": "Layer Groups"},
        ),
        migrations.AlterModelOptions(
            name="ogcserver",
            options={"verbose_name": "OGC Server", "verbose_name_plural": "OGC Servers"},
        ),
        migrations.AlterModelOptions(
            name="publishedaslayerwms",
            options={"verbose_name": "WMS Layer", "verbose_name_plural": "WMS Layers"},
        ),
        migrations.AlterModelOptions(
            name="publishedastheme",
            options={
                "ordering": ["ordering"],
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
            },
        ),
        migrations.AlterField(
            model_name="publishedaslayerwms",
            name="max_resolution_hint",
            field=models.FloatField(default=999999999.0),
        ),
        migrations.AlterField(
            model_name="publishedaslayerwms",
            name="min_resolution_hint",
            field=models.FloatField(default=0.0),
        ),
    ]
