# Generated by Django 5.0.6 on 2025-05-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webgis", "0005_alter_layergroupmp_options_alter_ogcserver_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publishedaslayerwms",
            name="child_layers",
        ),
    ]
