# Generated by Django 5.0.6 on 2025-05-30 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webgis", "0006_remove_publishedaslayerwms_child_layers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishedaslayerwms",
            name="layer_group",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wms_datasets",
                related_query_name="wms_dataset",
                to="webgis.layergroupmp",
            ),
        ),
    ]
