# Generated by Django 5.0.6 on 2025-05-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webgis", "0007_alter_publishedaslayerwms_layer_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ogcserver",
            name="mandant",
        ),
    ]
