# Generated by Django 5.0.6 on 2025-05-30 13:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webgis", "0008_remove_ogcserver_mandant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="layergroupmp",
            options={"verbose_name": "Group", "verbose_name_plural": "Groups"},
        ),
        migrations.RemoveField(
            model_name="publishedastheme",
            name="project",
        ),
        migrations.RemoveField(
            model_name="publishedastheme",
            name="themes_json_id",
        ),
        migrations.AddField(
            model_name="publishedastheme",
            name="themes_json_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
