# Generated by Django 5.0.6 on 2025-05-30 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_integration", "0023_remove_customdataset_style_and_more"),
        ("webgis", "0009_alter_layergroupmp_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedastheme",
            name="project",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="published_as_geogirafe_themes",
                related_query_name="published_as_geogirafe_theme",
                to="data_integration.project",
            ),
        ),
    ]
