# Generated by Django 5.0.6 on 2025-06-01 18:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webgis", "0010_publishedastheme_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layergroupmp",
            name="themes_json_id",
        ),
        migrations.AddField(
            model_name="layergroupmp",
            name="themes_json_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
