# Generated by Django 5.0.6 on 2025-06-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webgis", "0011_remove_layergroupmp_themes_json_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ogcserver",
            name="name",
            field=models.CharField(null=True, unique=True),
        ),
    ]
