# Generated by Django 5.0.6 on 2025-06-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webgis", "0012_alter_ogcserver_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="layergroupmp",
            name="title",
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
