# Generated by Django 5.0.6 on 2025-06-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webgis", "0013_layergroupmp_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedaslayerwms",
            name="queryable",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
