# Generated by Django 5.0.6 on 2025-06-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webgis", "0015_alter_publishedaslayerwms_custom_dataset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishedaslayerwms",
            name="dimensions",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="publishedaslayerwms",
            name="metadata",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="publishedaslayerwms",
            name="queryable",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="publishedaslayerwmts",
            name="dimensions",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="publishedaslayerwmts",
            name="metadata",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
