# Generated by Django 5.0.6 on 2025-06-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webgis", "0016_alter_publishedaslayerwms_dimensions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishedaslayerwms",
            name="queryable",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
