# Generated by Django 5.0.6 on 2025-08-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webgis", "0017_alter_publishedaslayerwms_queryable"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedaslayerwms",
            name="extent",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="publishedaslayerwms",
            name="preview",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
