# Generated by Django 5.0.6 on 2025-08-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webgis", "0017_alter_publishedaslayerwms_queryable"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedaslayerwms",
            name="extent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publishedaslayerwms",
            name="preview",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
