# Generated by Django 5.0.6 on 2025-08-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webgis", "0018_publishedaslayerwms_extent_and_more"),
        ("webgis", "0019_publishedaslayerwms_extent_wgs84"),
    ]

    operations = []
