# Generated by Django 5.2.10 on 2026-02-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0020_merge_20250815_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layergroupmp',
            name='path',
            field=models.TextField(max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='layergroupmp',
            name='name',
            field=models.TextField(max_length=2048),
        ),
    ]
