# Generated by Django 5.2.10 on 2026-02-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webgis", "0021_alter_layergroupmp_path"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publishedastheme",
            options={
                "ordering": ["ordering"],
                "permissions": [
                    ("can_manage_object_permissions", "Can manage object permissions")
                ],
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
            },
        ),
    ]
