# Generated by Django 5.2.10 on 2026-02-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webgis", "0022_alter_publishedastheme_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedastheme",
            name="location",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publishedastheme",
            name="zoom",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
