# Generated by Django 5.2.10 on 2026-03-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webgis", "0023_publishedastheme_location_publishedastheme_zoom"),
    ]

    operations = [
        migrations.CreateModel(
            name="UrlShortener",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
                ("url", models.CharField()),
            ],
        ),
    ]
