# Generated by Django 5.2.14 on 2026-08-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0024_urlshortener'),
    ]

    operations = [
        migrations.AddField(
            model_name='layergroupmp',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layergroupmp',
            name='is_expanded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publishedaslayerwms',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publishedaslayerwmts',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
