# Generated by Django 5.2.16 on 2026-09-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0025_layergroupmp_is_checked_layergroupmp_is_expanded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedaslayerwms',
            name='is_background',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publishedaslayerwmts',
            name='is_background',
            field=models.BooleanField(default=False),
        ),
    ]
