# Generated by Django 5.2.16 on 2026-09-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0026_publishedaslayerwms_is_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedaslayerwms',
            name='thumbnail',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='publishedaslayerwmts',
            name='thumbnail',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
