# Generated by Django 5.0.6 on 2024-07-26 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('version', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('bbox', models.CharField(max_length=1000)),
                ('path', models.CharField(max_length=10000)),
                ('style', models.TextField()),
                ('driver', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', related_query_name='dataset', to='qmeleon.project')),
            ],
        ),
    ]
