# Generated by Django 5.0.6 on 2024-08-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmeleon', '0003_rasterdataset_vectordataset_field_delete_dataset'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('name', 'vector_dataset')},
        ),
        migrations.AlterUniqueTogether(
            name='rasterdataset',
            unique_together={('name', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='vectordataset',
            unique_together={('name', 'project')},
        ),
    ]
