# Generated by Django 5.0.6 on 2024-08-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeleon', '0004_alter_field_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasterdataset',
            name='source',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='vectordataset',
            name='source',
            field=models.JSONField(default=dict),
        ),
    ]
