# Generated by Django 5.0.6 on 2024-08-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeleon', '0005_rasterdataset_source_vectordataset_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hash',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
