# Generated by Django 5.0.6 on 2024-08-23 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeleon', '0006_project_hash'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='integration_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'version', 'group')},
        ),
    ]
