# Generated by Django 5.0.6 on 2024-08-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeleon', '0008_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasterdataset',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vectordataset',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
