# Generated by Django 5.0.6 on 2024-08-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeleon', '0009_alter_rasterdataset_name_alter_vectordataset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasterdataset',
            name='qgis_layer_id',
            field=models.CharField(default='intermediate', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vectordataset',
            name='qgis_layer_id',
            field=models.CharField(default='intermediate', max_length=1000),
            preserve_default=False,
        ),
    ]
