# Generated by Django 5.0.6 on 2024-08-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeleon', '0010_rasterdataset_qgis_layer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasterdataset',
            name='crs',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='vectordataset',
            name='crs',
            field=models.JSONField(default=dict),
        ),
    ]
