# Generated by Django 5.0.6 on 2024-09-06 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeleon', '0012_rasterdataset_bbox_wgs84_vectordataset_bbox_wgs84'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('qgis_layer_id', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('bbox', models.CharField(max_length=1000)),
                ('bbox_wgs84', models.CharField(max_length=1000)),
                ('path', models.CharField(max_length=10000)),
                ('source', models.JSONField(default=dict)),
                ('style', models.TextField()),
                ('driver', models.CharField(max_length=50)),
                ('crs', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_datasets', related_query_name='custom_dataset', to='qmeleon.project')),
            ],
            options={
                'unique_together': {('name', 'project')},
            },
        ),
    ]
