# Generated by Django 5.0.6 on 2024-09-18 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeleon', '0014_mandant_alter_project_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mandant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandants', related_query_name='mandant', to='qmeleon.mandant'),
        ),
    ]
