# Generated by Django 5.0.6 on 2024-09-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeleon', '0015_alter_project_mandant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandant',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
