from xml.etree.ElementTree import QName

from georama.maps.interfaces.ogc import wfs_2_0_0
from georama.maps.maps_config import Config


class TestMapsConfig:
    def test_wfs_2_0_0_capabilities_config(self):
        url = "http://localhost:4242/maps?"
        config = Config().wfs_2_0_0_capabilities_config(url)

        version = "2.0.0"
        expected_wfs_capabilities = wfs_2_0_0.WfsCapabilities(
            feature_type_list=wfs_2_0_0.FeatureTypeList(feature_type=[]),
            filter_capabilities=wfs_2_0_0.FilterCapabilities(
                conformance=wfs_2_0_0.ConformanceType(
                    constraint=[
                        wfs_2_0_0.DomainType(
                            default_value=wfs_2_0_0.DefaultValue(value="TRUE"),
                            name="ImplementsQuery",
                        ),
                        wfs_2_0_0.DomainType(
                            default_value=wfs_2_0_0.DefaultValue(value="TRUE"),
                            name="ImplementsAdHocQuery",
                        ),
                        wfs_2_0_0.DomainType(
                            default_value=wfs_2_0_0.DefaultValue(value="TRUE"),
                            name="ImplementsFunctions",
                        ),
                        wfs_2_0_0.DomainType(
                            default_value=wfs_2_0_0.DefaultValue(value="TRUE"),
                            name="ImplementsResourceId",
                        ),
                        wfs_2_0_0.DomainType(
                            default_value=wfs_2_0_0.DefaultValue(value="TRUE"),
                            name="ImplementsMinStandardFilter",
                        ),
                        wfs_2_0_0.DomainType(
                            default_value=wfs_2_0_0.DefaultValue(value="TRUE"),
                            name="ImplementsStandardFilter",
                        ),
                        wfs_2_0_0.DomainType(
                            default_value=wfs_2_0_0.DefaultValue(value="TRUE"),
                            name="ImplementsMinSpatialFilter",
                        ),
                        wfs_2_0_0.DomainType(
                            default_value=wfs_2_0_0.DefaultValue(value="TRUE"),
                            name="ImplementsSpatialFilter",
                        ),
                        wfs_2_0_0.DomainType(
                            default_value=wfs_2_0_0.DefaultValue(value="FALSE"),
                            name="ImplementsMinTemporalFilter",
                        ),
                        wfs_2_0_0.DomainType(
                            default_value=wfs_2_0_0.DefaultValue(value="FALSE"),
                            name="ImplementsTemporalFilter",
                        ),
                        wfs_2_0_0.DomainType(
                            default_value=wfs_2_0_0.DefaultValue(value="FALSE"),
                            name="ImplementsVersionNav",
                        ),
                        wfs_2_0_0.DomainType(
                            default_value=wfs_2_0_0.DefaultValue(value="TRUE"),
                            name="ImplementsSorting",
                        ),
                        wfs_2_0_0.DomainType(
                            default_value=wfs_2_0_0.DefaultValue(value="FALSE"),
                            name="ImplementsExtendedOperators",
                        ),
                        wfs_2_0_0.DomainType(
                            default_value=wfs_2_0_0.DefaultValue(value="TRUE"),
                            name="ImplementsMinimumXPath",
                        ),
                        wfs_2_0_0.DomainType(
                            default_value=wfs_2_0_0.DefaultValue(value="FALSE"),
                            name="ImplementsSchemaElementFunc",
                        ),
                    ]
                ),
                id_capabilities=wfs_2_0_0.IdCapabilitiesType(
                    resource_identifier=[
                        wfs_2_0_0.ResourceIdentifierType(
                            name=QName(text_or_uri="fes:ResourceId"),
                        )
                    ]
                ),
                scalar_capabilities=wfs_2_0_0.ScalarCapabilitiesType(
                    comparison_operators=wfs_2_0_0.ComparisonOperatorsType(
                        comparison_operator=[
                            wfs_2_0_0.ComparisonOperatorType(
                                name="PropertyIsEqualTo",
                            ),
                            wfs_2_0_0.ComparisonOperatorType(
                                name="PropertyIsNotEqualTo",
                            ),
                            wfs_2_0_0.ComparisonOperatorType(
                                name="PropertyIsLessThan",
                            ),
                            wfs_2_0_0.ComparisonOperatorType(
                                name="PropertyIsGreaterThan",
                            ),
                            wfs_2_0_0.ComparisonOperatorType(
                                name="PropertyIsLessThanOrEqualTo",
                            ),
                            wfs_2_0_0.ComparisonOperatorType(
                                name="PropertyIsGreaterThanOrEqualTo",
                            ),
                            wfs_2_0_0.ComparisonOperatorType(
                                name="PropertyIsLike",
                            ),
                            wfs_2_0_0.ComparisonOperatorType(
                                name="PropertyIsBetween",
                            ),
                        ]
                    )
                ),
                spatial_capabilities=wfs_2_0_0.SpatialCapabilitiesType(
                    geometry_operands=wfs_2_0_0.GeometryOperandsType(
                        geometry_operand=[
                            wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                name=QName(text_or_uri="gml:Point"),
                            ),
                            wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                name=QName(text_or_uri="gml:MultiPoint"),
                            ),
                            wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                name=QName(text_or_uri="gml:LineString"),
                            ),
                            wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                name=QName(text_or_uri="gml:MultiLineString"),
                            ),
                            wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                name=QName(text_or_uri="gml:Curve"),
                            ),
                            wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                name=QName(text_or_uri="gml:MultiCurve"),
                            ),
                            wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                name=QName(text_or_uri="gml:Polygon"),
                            ),
                            wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                name=QName(text_or_uri="gml:MultiPolygon"),
                            ),
                            wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                name=QName(text_or_uri="gml:Surface"),
                            ),
                            wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                name=QName(text_or_uri="gml:MultiSurface"),
                            ),
                            wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                name=QName(text_or_uri="gml:Box"),
                            ),
                            wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                name=QName(text_or_uri="gml:Envelope"),
                            ),
                        ]
                    ),
                    spatial_operators=wfs_2_0_0.SpatialOperatorsType(
                        spatial_operator=[
                            wfs_2_0_0.SpatialOperatorType(
                                geometry_operands=wfs_2_0_0.GeometryOperandsType(
                                    geometry_operand=[
                                        wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                            name=QName(text_or_uri="Equals"),
                                        ),
                                        wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                            name=QName(text_or_uri="Disjoint"),
                                        ),
                                        wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                            name=QName(text_or_uri="Touches"),
                                        ),
                                        wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                            name=QName(text_or_uri="Within"),
                                        ),
                                        wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                            name=QName(text_or_uri="Overlaps"),
                                        ),
                                        wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                            name=QName(text_or_uri="Crosses"),
                                        ),
                                        wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                            name=QName(text_or_uri="Intersects"),
                                        ),
                                        wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                            name=QName(text_or_uri="Contains"),
                                        ),
                                        wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                            name=QName(text_or_uri="DWithin"),
                                        ),
                                        wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                            name=QName(text_or_uri="Beyond"),
                                        ),
                                        wfs_2_0_0.GeometryOperandsTypeGeometryOperand(
                                            name=QName(text_or_uri="BBOX"),
                                        ),
                                    ]
                                )
                            )
                        ]
                    ),
                ),
                temporal_capabilities=wfs_2_0_0.TemporalCapabilitiesType(
                    temporal_operands=wfs_2_0_0.TemporalOperandsType(
                        temporal_operand=[
                            wfs_2_0_0.TemporalOperandsTypeTemporalOperand(
                                name=QName(text_or_uri="gml:TimePeriod"),
                            ),
                            wfs_2_0_0.TemporalOperandsTypeTemporalOperand(
                                name=QName(text_or_uri="gml:TimeInstant"),
                            ),
                        ]
                    ),
                    temporal_operators=wfs_2_0_0.TemporalOperatorsType(
                        temporal_operator=[
                            wfs_2_0_0.TemporalOperatorType(
                                temporal_operands=wfs_2_0_0.TemporalOperandsType(
                                    temporal_operand=[
                                        wfs_2_0_0.TemporalOperandsTypeTemporalOperand(
                                            name=QName(text_or_uri="During"),
                                        )
                                    ]
                                )
                            )
                        ]
                    ),
                ),
            ),
            operations_metadata=wfs_2_0_0.OperationsMetadata(
                constraint=[
                    wfs_2_0_0.DomainType(
                        name="ImplementsBasicWFS",
                        default_value=wfs_2_0_0.DefaultValue(value="TRUE"),
                    ),
                    wfs_2_0_0.DomainType(
                        name="ImplementsTransactionalWFS",
                        default_value=wfs_2_0_0.DefaultValue(value="FALSE"),
                    ),
                    wfs_2_0_0.DomainType(
                        name="ImplementsLockingWFS",
                        default_value=wfs_2_0_0.DefaultValue(value="FALSE"),
                    ),
                    wfs_2_0_0.DomainType(
                        name="KVPEncoding", default_value=wfs_2_0_0.DefaultValue(value="FALSE")
                    ),
                    wfs_2_0_0.DomainType(
                        name="XMLEncoding", default_value=wfs_2_0_0.DefaultValue(value="TRUE")
                    ),
                    wfs_2_0_0.DomainType(
                        name="SOAPEncoding",
                        default_value=wfs_2_0_0.DefaultValue(value="FALSE"),
                    ),
                    wfs_2_0_0.DomainType(
                        name="ImplementsInheritance",
                        default_value=wfs_2_0_0.DefaultValue(value="FALSE"),
                    ),
                    wfs_2_0_0.DomainType(
                        name="ImplementsRemoteResolve",
                        default_value=wfs_2_0_0.DefaultValue(value="FALSE"),
                    ),
                    wfs_2_0_0.DomainType(
                        name="ImplementsResultPaging",
                        default_value=wfs_2_0_0.DefaultValue(value="TRUE"),
                    ),
                    wfs_2_0_0.DomainType(
                        name="ImplementsStandardJoins",
                        default_value=wfs_2_0_0.DefaultValue(value="FALSE"),
                    ),
                    wfs_2_0_0.DomainType(
                        name="ImplementsSpatialJoins",
                        default_value=wfs_2_0_0.DefaultValue(value="FALSE"),
                    ),
                    wfs_2_0_0.DomainType(
                        name="ImplementsTemporalJoins",
                        default_value=wfs_2_0_0.DefaultValue(value="FALSE"),
                    ),
                    wfs_2_0_0.DomainType(
                        name="ImplementsFeatureVersioning",
                        default_value=wfs_2_0_0.DefaultValue(value="FALSE"),
                    ),
                    wfs_2_0_0.DomainType(
                        name="ManageStoredQueries",
                        default_value=wfs_2_0_0.DefaultValue(value="FALSE"),
                    ),
                    wfs_2_0_0.DomainType(
                        name="PagingIsTransactionSafe",
                        default_value=wfs_2_0_0.DefaultValue(value="FALSE"),
                    ),
                    wfs_2_0_0.DomainType(
                        name="QueryExpressions",
                        choice=wfs_2_0_0.AllowedValues(
                            value_or_range=[
                                wfs_2_0_0.Value1(value="wfs:Query"),
                                wfs_2_0_0.Value1(value="wfs:StoredQuery"),
                            ]
                        ),
                    ),
                ],
                operation=[
                    wfs_2_0_0.Operation(
                        name="GetCapabilities",
                        dcp=[
                            wfs_2_0_0.Dcp(
                                http=wfs_2_0_0.Http(
                                    get_or_post=[
                                        wfs_2_0_0.Get(href=url),
                                        wfs_2_0_0.Post(href=url),
                                    ]
                                )
                            )
                        ],
                        parameter=[
                            wfs_2_0_0.DomainType(
                                name="AcceptVersions",
                                choice=wfs_2_0_0.AllowedValues(
                                    value_or_range=[wfs_2_0_0.Value1(value=version)]
                                ),
                            ),
                            wfs_2_0_0.DomainType(
                                name="AcceptFormats",
                                choice=wfs_2_0_0.AllowedValues(
                                    value_or_range=[wfs_2_0_0.Value1(value="text/xml")]
                                ),
                            ),
                            wfs_2_0_0.DomainType(
                                name="Sections",
                                choice=wfs_2_0_0.AllowedValues(
                                    value_or_range=[
                                        wfs_2_0_0.Value1(value="ServiceIdentification"),
                                        wfs_2_0_0.Value1(value="ServiceProvider"),
                                        wfs_2_0_0.Value1(value="OperationsMetadata"),
                                        wfs_2_0_0.Value1(value="FeatureTypeList"),
                                        wfs_2_0_0.Value1(value="Filter_Capabilities"),
                                    ]
                                ),
                            ),
                        ],
                    ),
                    wfs_2_0_0.Operation(
                        name="DescribeFeatureType",
                        dcp=[
                            wfs_2_0_0.Dcp(
                                http=wfs_2_0_0.Http(
                                    get_or_post=[
                                        wfs_2_0_0.Get(href=url),
                                        wfs_2_0_0.Post(href=url),
                                    ]
                                )
                            )
                        ],
                        parameter=[
                            wfs_2_0_0.DomainType(
                                name="outputFormat",
                                choice=wfs_2_0_0.AllowedValues(
                                    value_or_range=[
                                        wfs_2_0_0.Value1(
                                            value="application/gml+xml; version=3.2"
                                        ),
                                        wfs_2_0_0.Value1(value="text/xml; subtype=gml/3.2.1"),
                                        wfs_2_0_0.Value1(value="text/json"),
                                    ]
                                ),
                            )
                        ],
                    ),
                    wfs_2_0_0.Operation(
                        name="GetFeature",
                        dcp=[
                            wfs_2_0_0.Dcp(
                                http=wfs_2_0_0.Http(
                                    get_or_post=[
                                        wfs_2_0_0.Get(href=url),
                                        wfs_2_0_0.Post(href=url),
                                    ]
                                )
                            )
                        ],
                        parameter=[
                            wfs_2_0_0.DomainType(
                                name="outputFormat",
                                choice=wfs_2_0_0.AllowedValues(
                                    value_or_range=[
                                        wfs_2_0_0.Value1(
                                            value="application/gml+xml; version=3.2"
                                        ),
                                        wfs_2_0_0.Value1(value="text/xml; subtype=gml/3.2.1"),
                                        wfs_2_0_0.Value1(value="text/json"),
                                    ]
                                ),
                            )
                        ],
                    ),
                    wfs_2_0_0.Operation(
                        name="GetPropertyValue",
                        dcp=[
                            wfs_2_0_0.Dcp(
                                http=wfs_2_0_0.Http(
                                    get_or_post=[
                                        wfs_2_0_0.Get(href=url),
                                        wfs_2_0_0.Post(href=url),
                                    ]
                                )
                            )
                        ],
                        parameter=[
                            wfs_2_0_0.DomainType(
                                name="outputFormat",
                                choice=wfs_2_0_0.AllowedValues(
                                    value_or_range=[
                                        wfs_2_0_0.Value1(
                                            value="application/gml+xml; version=3.2"
                                        ),
                                        wfs_2_0_0.Value1(value="text/xml; subtype=gml/3.2.1"),
                                        wfs_2_0_0.Value1(value="text/json"),
                                    ]
                                ),
                            )
                        ],
                    ),
                ],
                parameter=[
                    wfs_2_0_0.DomainType(
                        name="version",
                        choice=wfs_2_0_0.AllowedValues(
                            value_or_range=[wfs_2_0_0.Value1(value=version)]
                        ),
                    )
                ],
            ),
            service_identification=wfs_2_0_0.ServiceIdentification(
                title=[
                    wfs_2_0_0.Title1(
                        value="QGIS Server light WFS",
                    )
                ],
                abstract=[wfs_2_0_0.Abstract1(value="This is the new approach.")],
                keywords=[
                    wfs_2_0_0.Keywords(
                        keyword=[
                            wfs_2_0_0.LanguageStringType(value="fast", lang="en"),
                            wfs_2_0_0.LanguageStringType(value="scalable", lang="en"),
                        ]
                    )
                ],
                service_type=wfs_2_0_0.CodeType(value="WFS", code_space="OGC"),
                service_type_version=[version],
                fees=wfs_2_0_0.Fees(value="None"),
                access_constraints=[wfs_2_0_0.AccessConstraints(value="None")],
            ),
            service_provider=wfs_2_0_0.ServiceProvider(
                provider_name="OPENGIS.ch",
                provider_site=wfs_2_0_0.OnlineResourceType(href="https://opengis.ch"),
                service_contact=wfs_2_0_0.ResponsiblePartySubsetType(
                    contact_info=wfs_2_0_0.ContactInfo(
                        address=wfs_2_0_0.AddressType(
                            administrative_area="Canton Graubünden",
                            city="Laax",
                            country="Switzerland",
                            delivery_point=["OPENGIS.ch GmbH", "Via Geinas 2"],
                            electronic_mail_address=["sales@opengis.ch"],
                            postal_code="7031",
                        ),
                        hours_of_service="09:00 - 16:00",
                        online_resource=wfs_2_0_0.OnlineResourceType(
                            href="https://opengis.ch"
                        ),
                    ),
                    individual_name=wfs_2_0_0.IndividualName(
                        value="Rudert, Clemens",
                    ),
                    position_name=wfs_2_0_0.PositionName(
                        value="DEV",
                    ),
                ),
            ),
            version=version,
        )
        assert config == expected_wfs_capabilities
