# Generated by Django 5.2.10 on 2026-04-23 17:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0003_alter_publishedasdataset_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishedAsProcess",
            fields=[
                (
                    "identifier",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=1000, null=True
                    ),
                ),
                ("public", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(
                        blank=True, default=None, max_length=1000, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "license",
                    models.TextField(
                        default="\n    This dataset is made available under the Open Database\n    License: http://opendatacommons.org/licenses/odbl/1.0/.\n    Any rights in individual contents of the database are licensed\n    under the Database Contents\n    License: http://opendatacommons.org/licenses/dbcl/1.0/\n    "
                    ),
                ),
                ("fees", models.TextField(default="No fees apply.")),
                (
                    "access_constraints",
                    models.TextField(default="No access constraints apply."),
                ),
                ("process_id", models.CharField(db_index=True, unique=True)),
            ],
            options={
                "verbose_name": "Process",
                "verbose_name_plural": "Processes",
                "permissions": [
                    ("can_manage_object_permissions", "Can manage object permissions")
                ],
            },
        ),
        migrations.AlterField(
            model_name="job",
            name="process",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="processes.publishedasprocess",
            ),
        ),
        migrations.DeleteModel(
            name="Process",
        ),
    ]
