# Generated by Django 5.2.14 on 2026-05-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0004_publishedasprocess_alter_job_process_delete_process"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publishedasprocess",
            name="description",
        ),
        migrations.RemoveField(
            model_name="publishedasprocess",
            name="title",
        ),
        migrations.AlterField(
            model_name="job",
            name="job_result",
            field=models.JSONField(null=True),
        ),
    ]
