services:
  georama:
    env_file:
      - .env
    environment:
      - "GEORAMA_QSL_EXPORTER_URL=http://qsl-exporter:5000/export"
      - "QSL_REDIS_URL=redis://qsl-redis:6379"
    image: local/georama:dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        PYTHON_VERSION: "${PY_VERSION:-3.12}"
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
        QSL_SOURCE_BRANCH: "${QSL_SOURCE_BRANCH:-master}"
    develop:
      watch:
        - action: rebuild
          path: uv.lock
        - action: rebuild
          path: Dockerfile
    ports:
      - "4242:4242"
      - "4222:2222"
    volumes:
      - ./:/app
      - georama-venv:/.venv
      - georama-static:/georama/static
      - ssh_host_keys:/etc/ssh
      - ./docker/sshd_config.conf:/etc/ssh/sshd_config
    depends_on:
      georama-db:
        condition: service_healthy
      qsl-redis:
        condition: service_healthy
  georama-db:
    platform: "linux/amd64"
    restart: unless-stopped
    image: postgis/postgis:17-3.5
    volumes:
      - "georama-db:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_USER=${GEORAMA_DB_USER?}"
      - "POSTGRES_PASSWORD=${GEORAMA_DB_PW?}"
      - "POSTGRES_DB=${GEORAMA_DB_NAME?}"
    healthcheck:
      test: psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT PostGIS_Version()'
      interval: 0.1s
      timeout: 1s
      retries: 50
  qsl-redis:
    image: redis:8.8.0
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 0.5s
      retries: 50
  qsl:
    platform: "linux/amd64"
    restart: unless-stopped
    image: opengisch/qgis-server-light-dev:latest
    env_file:
      - .env
    environment:
      - "QSL_REDIS_URL=redis://qsl-redis:6379"
      - "QSL_SVG_PATH=/io/svg"
      - "QSL_DATA_ROOT=/io/data"
    volumes:
      - "./tests/resources/projects:/io/data:ro"
    deploy:
      replicas: 1
    depends_on:
      qsl-redis:
        condition: service_healthy
  qsl-exporter:
    platform: "linux/amd64"
    restart: unless-stopped
    image: opengisch/qgis-server-light-dev:latest
    env_file:
      - .env
    environment:
      - "QSL_DATA_ROOT=/io/data"
    ports:
      - "5000:5000"
    command:
      - "serve-exporter-api-outbound"
    volumes:
      - "./tests/resources/projects:/io/data"
  geogirafe:
    image: geogirafe/viewer:latest
    restart: unless-stopped
    volumes:
      - ./geogirafe/config.json:/var/www/localhost/htdocs/config.json
      - ./geogirafe/config.mobile.json:/var/www/localhost/htdocs/config.mobile.json
    ports:
      - "9309:443"
      - "9308:80"
volumes:
  georama-venv:
  georama-static:
  georama-db:
  ssh_host_keys:
