services:
  georama:
    image: georama:dev
    env_file:
      - .env
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
      - "${GEORAMA_LOCAL_DATA:-./tests/resources/projects}:/io/data:ro"
    ports:
      - "4242:4242"
  georama-db:
    image: postgis/postgis:14-3.4
    volumes:
      - "georama-db_data:/var/lib/postgresql/data"
    ports:
      - "54321:5432"
    environment:
      - "POSTGRES_USER=${GEORAMA_DB_USER:-postgres}"
      - "POSTGRES_PASSWORD=${GEORAMA_DB_PW:-test}"
      - "POSTGRES_DB=${GEORAMA_DB_NAME:-postgres}"
  georama-test_data:
    image: postgis/postgis:14-3.4
    volumes:
      - "georama-test_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=${GEORAMA_DB_USER:-postgres}"
      - "POSTGRES_PASSWORD=${GEORAMA_DB_PW:-test}"
      - "POSTGRES_DB=${GEORAMA_DB_NAME:-postgres}"
  qsl-redis:
    image: redis:7.4.0
    ports:
      - "1234:6379"
  qsl:
    restart: unless-stopped
    image: opengisch/qgis-server-light:latest
    env_file:
      - .env
    volumes:
      - "${GEORAMA_LOCAL_DATA:-./tests/resources/projects}:/io/data:ro"
    deploy:
      replicas: 1
  geogirafe:
    image: geogirafe/viewer:latest
    volumes:
      - ./geogirafe/config.json:/var/www/localhost/htdocs/config.json
    ports:
      - "9309:443"
      - "9308:80"

volumes:
  georama-db_data:
  georama-test_data: