[project]
name = "georama"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Clemens Rudert", email = "crud3_rt@posteo.ch" }
]
requires-python = ">=3.12"
dependencies = [
    "django[argon2]>=6.0.6",
    "django-configurations>=2.5.1",
    "django-cors-headers>=4.9.0",
    "django-filter>=25.2",
    "django-guardian>=3.3.1",
    "psycopg[pool]>=3.3.4",
    "django-unfold>=0.96.0",
    "uvicorn>=0.49.0",
    "django-extensions>=4.1",
    "djangorestframework>=3.17.1",
    "drf-spectacular[sidecar]>=0.29.0",
    "djangorestframework-gis>=1.2.1",
    "django-allauth[socialaccount]>=65.18.0",
    "adrf>=0.1.13",
    "django-crispy-forms>=2.6",
    "crispy-bootstrap5>=2026.3",
    "pygeoapi==0.21.0",
    "qgis_server_light[interface] @ git+https://github.com/opengisch/qgis-server-light.git@refactoring",
    "xsdata>=26.2",
    "sqlalchemy>=2.0.51",
    "geoalchemy2>=0.20.0",
    "psycopg2-binary>=2.9.12",
    "gdal==3.10.3",
    "httpx>=0.28.1",
    "redis==5.0.8",
]

[project.scripts]
manage = "georama.manage:main"
[build-system]
requires = ["uv_build>=0.11.15,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    { include-group = "lint-format" },
    { include-group = "test" },
    "django-extensions>=4.1",
    "django-silk>=5.5.0",
    "factory-boy>=3.3.3",
    "pre-commit",
    "pyproj>=3.7.2",
    "shapely>=2.1.2",
    "qgis-server-light[interface]",
]
lint-format = [
    "ruff>=0.15.15",
]
test = [
    "pytest>=9.0.3",
    "pytest-django>=4.12.0",
    "pytest-lazy-fixtures>=1.4.0",
]

[tool.uv.sources]
qgis-server-light = { path = "/qsl", editable = true }

[tool.ruff]
target-version = "py312"
line-length = 100
extend-exclude = [
    "src/georama/maps/interfaces/**",
    "src/georama/*/migrations/**",
]
[tool.ruff.lint]
extend-select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "Q", # Quotes
    "UP", # pyupgrade replacement
    "B", # bugbear
    "SIM", # simplify
    "I", # isort
]
fixable = ["ALL"]

[tool.pytest.ini_options]
addopts = "-vra --dc=Test"
DJANGO_SETTINGS_MODULE = "georama.settings"
testpaths = [
    "tests",
]
python_files = ["test_*.py"]
