# BUILD

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

# Poetry

# Information required for building (sdist/wheel)
## Also renders on pypi as 'subtitle'
[project]
name = "georama"
version = "0.0.1"
description = "The habitat of geoanimals"
authors = [
    {name="Clemens Rudert", email="clemens@opengis.ch"}
]
requires-python = ">=3.10.4"
maintainers = [
    {name="Clemens Rudert", email="clemens@opengis.ch"}
]
# license = "AGPL-3.0-only"
urls.Tracker = "https://github.com/georama/issues"
urls.CI = "https://github.com/opengisch/georama/actions"
urls.Documentation = "https://georama.readthedocs.io/"
urls.Source = "https://github.com/opengisch/georama"
urls.Changelog = "https://github.com/opengisch/georama/blob/master/CHANGELOG.md"
urls.Contributing = "https://github.com/opengisch/georama/blob/master/CONTRIBUTING.md"
keywords = [
    "python package",
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Natural Language :: English",
    "Operating System :: Unix",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed"
]

# PyPi url links, that appear in 'Project Links' section



# Caret requirements allow SemVer compatible updates to a specified version. An update is allowed if the new version number does not modify the left-most non-zero digit in the major, minor, patch grouping. For instance, if we previously ran poetry add requests@^2.13.0 and wanted to update the library and ran poetry update requests, poetry would update us to version 2.14.0 if it was available, but would not update us to 3.0.0. If instead we had specified the version string as ^0.1.13, poetry would update to 0.1.14 but not 0.2.0. 0.0.x is not considered compatible with any other version.
# REQUIREMENT  VERSIONS ALLOWED
# ^1.2.3	   >=1.2.3 <2.0.0
# ^1.2	       >=1.2.0 <2.0.0
# ^1	       >=1.0.0 <2.0.0
# ^0.2.3	   >=0.2.3 <0.3.0
# ^0.0.3	   >=0.0.3 <0.0.4
# ^0.0	       >=0.0.0 <0.1.0
# ^0	       >=0.0.0 <1.0.0
# "~" is the more conservative compared to "^"
# Tilde requirements specify a minimal version with some ability to update. If you specify a major, minor, and patch version or only a major and minor version, only patch-level changes are allowed. If you only specify a major version, then minor- and patch-level changes are allowed.
# REQUIREMENT  VERSIONS ALLOWED
# ~1.2.3	   >=1.2.3 <1.3.0
# ~1.2	       >=1.2.0 <1.3.0
# ~1	       >=1.0.0 <2.0.0


### Dependency Constraints, aka Requirements ###
dependencies = [
    "click==8.1.7",
    "pygeoapi==0.17.0",
    "django==5.0.6",
    "django-jazzmin==3.0.0",
    "gdal==3.9.1",
    "psycopg2==2.9.9",
    "geoalchemy2==0.15.2",
    "SQLAlchemy<2.0.0",
    "xsdata[cli,lxml,soap]==24.6.1",
    "async-timeout==4.0.3",
    "redis==5.0.8",
    # "qgis_server_light @ git+ssh://git@github.com/opengisch/qgis-server-light.git@master",
    "qgis-server-light==0.0.2",
    # deps for clogs
    "django-allauth==0.63.3",
    "django-cors-headers==4.3.1",
    "django-ninja== 0.22.2",
    "django-cors-headers==4.3.1",
    "django-treebeard==4.7.1",
    "djangorestframework==3.15.1",
    "django-admin-sortable2==2.2.1",
    "django-simple-history==3.7.0",
    "djangorestframework-gis @ git+https://github.com/openwisp/django-rest-framework-gis@4f244d5d8a7ad5b453fd04f64150818d15123e01"
]

# Test: packages imported in test code and packages required for the "test runner"
optional-dependencies.test = [
    "pytest==8.0.0",
    "pytest-cov==5.0.0",
    "pytest-explicit==1.0.1",
    "pytest-xdist==3.5.0",
    "pytest-click==1.1.0",
    "pytest-run-subprocess==0.10.0"
]
# Type Checking
optional-dependencies.check =[
    "mypy==1.8.0"
]
# Docs: dev and build dependencies
optional-dependencies.docs = [
    "mkdocs==1.6.1",
    "mkdocs-macros-plugin==1.0.5",
    "mkdocs-material==9.5.34",
    "mkdocs-mermaid2-plugin==1.1.1",
    "mkdocs-section-index==0.3.8",
    "mkdocs-gen-files==0.5.0",
    "mkdocstrings==0.25.2",
    "mkdocstrings-python==1.10.9",
    "mkdocs-literate-nav==0.6.1",
    "pymdown-extensions==10.5",
    "mkdocs-click==0.8.1",
    "griffe==1.2.0"
]

[tool.setuptools.dynamic]
version = {attr = "georama.version"}  # any module attribute compatible with ast.literal_eval
readme = {file = ["README.md", "CHANGELOG.md"]}

[tool.setuptools.packages.find]
where = ["src"]

# TOOLS
[tool.pytest.ini_options]
minversion = "6.2"
addopts = "--strict-markers"
markers = [
    "slow: Marks a slow test",
    "integration: Integration Tests",
    "network_bound: Require internet connection",
]
testpaths = [
    "tests",
]
explicit-only = [
    "integration",
    "network_bound",
]

[tool.black]
line-length = 95
include = '\.pyi?$'
extend-exclude = '''
'''

[tool.isort]
profile = 'black'

[tool.bandit]
tests = []
skips = [
    "B101",
]

[tool.software-release]
version_variable = "src/georama/__init__.py:__version__"

[virtualenvs]
create = true
in-project = true
