# Generated by Django 6.0.6 on 2026-07-02 13:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_use_manage_api', 'Can use the management API')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identifier of the datasource.', primary_key=True, serialize=False)),
                ('qgis_layer_id', models.CharField(help_text='Layer identifier from the source QGIS project.', max_length=1000)),
                ('name', models.CharField(help_text='Name of the datasource.', max_length=1000)),
                ('bbox', models.CharField(help_text='Bounding box of the datasource in the source coordinate reference system.', max_length=1000)),
                ('bbox_wgs84', models.CharField(help_text='Bounding box of the datasource transformed to WGS84.', max_length=1000)),
                ('source', models.JSONField(default=dict, help_text='Source configuration and connection metadata of the datasource.')),
                ('styles', models.JSONField(default=dict, help_text='Rendered style definitions associated with this datasource.')),
                ('driver', models.CharField(help_text='Provider driver name used to access the datasource.', max_length=50)),
                ('crs', models.JSONField(default=dict, help_text='Coordinate reference system of the datasource.')),
                ('minimum_scale', models.FloatField(help_text='Minimum scale at which the datasource is visible.', null=True)),
                ('maximum_scale', models.FloatField(help_text='Maximum scale at which the datasource is visible.', null=True)),
            ],
            options={
                'verbose_name': 'datasource',
                'verbose_name_plural': 'datasources',
            },
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integration.datasource')),
            ],
            options={
                'verbose_name': 'custom',
                'verbose_name_plural': 'custom',
            },
            bases=('integration.datasource',),
        ),
        migrations.CreateModel(
            name='Raster',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integration.datasource')),
            ],
            options={
                'verbose_name': 'raster',
                'verbose_name_plural': 'rasters',
            },
            bases=('integration.datasource',),
        ),
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integration.datasource')),
                ('geometry_type_simple', models.CharField(help_text='Simplified geometry type of the vector datasource (eg. point, line, polygon).', max_length=1000)),
                ('geometry_type_wkb', models.CharField(help_text='Geometry type of the vector datasource.', max_length=1000)),
            ],
            options={
                'verbose_name': 'vector',
                'verbose_name_plural': 'vectors',
            },
            bases=('integration.datasource',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identifier of the project.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the project.', max_length=1000)),
                ('path', models.CharField(help_text='Path to the qgis project.', unique=True)),
                ('qgis_version', models.CharField(blank=True, help_text='QGIS version the project was created with.', max_length=1000)),
                ('hash', models.CharField(blank=True, help_text='Hash used to detect changes in project content.', max_length=20000)),
                ('organisation', models.ForeignKey(blank=True, help_text='Organisation this project belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.organisation')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'unique_together': {('name', 'organisation')},
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='project',
            field=models.ForeignKey(help_text='Project the datasource belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='datasources', to='integration.project'),
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('qgis_layer_id', 'project')},
        ),
        migrations.CreateModel(
            name='VectorField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identifier of the field.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Original field name from the source datasource.', max_length=1000)),
                ('type', models.CharField(help_text='Original data type from the source datasource.', max_length=1000)),
                ('is_primary_key', models.BooleanField(default=False, help_text='Whether this field is the datasource primary key.')),
                ('type_wfs', models.CharField(help_text='Field datatype exposed through WFS.', max_length=1000)),
                ('type_oapif', models.CharField(help_text='Field datatype exposed through OGC API Features.', max_length=1000)),
                ('type_oapif_format', models.CharField(help_text='Output format for the OGC API Features field type.', max_length=1000)),
                ('alias', models.CharField(help_text='Human-readable field label.', max_length=1000)),
                ('comment', models.CharField(help_text='Comment or description of the field.', max_length=1000)),
                ('nullable', models.BooleanField(default=True, help_text='Whether this field can store null values.')),
                ('length', models.IntegerField(help_text='....', null=True)),
                ('precision', models.IntegerField(help_text='Numeric precision.', null=True)),
                ('datasource', models.ForeignKey(help_text='Vector datasource this field belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='integration.vector')),
            ],
            options={
                'verbose_name': 'field',
                'verbose_name_plural': 'fields',
                'unique_together': {('name', 'datasource')},
            },
        ),
    ]
