# Generated by Django 6.0.6 on 2026-06-16 10:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('qgis_layer_id', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('bbox', models.CharField(max_length=1000)),
                ('bbox_wgs84', models.CharField(max_length=1000)),
                ('source', models.JSONField(default=dict)),
                ('styles', models.JSONField(default=dict)),
                ('driver', models.CharField(max_length=50)),
                ('crs', models.JSONField(default=dict)),
                ('minimum_scale', models.FloatField(null=True)),
                ('maximum_scale', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'dataset',
                'verbose_name_plural': 'datasets',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organisation')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
            },
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('dataset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integration.dataset')),
            ],
            options={
                'verbose_name': 'custom',
                'verbose_name_plural': 'custom',
            },
            bases=('integration.dataset',),
        ),
        migrations.CreateModel(
            name='Raster',
            fields=[
                ('dataset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integration.dataset')),
            ],
            options={
                'verbose_name': 'raster',
                'verbose_name_plural': 'rasters',
            },
            bases=('integration.dataset',),
        ),
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('dataset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integration.dataset')),
                ('geometry_type_simple', models.CharField(max_length=1000)),
                ('geometry_type_wkb', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'vector',
                'verbose_name_plural': 'vectors',
            },
            bases=('integration.dataset',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('version', models.CharField(blank=True, max_length=1000)),
                ('hash', models.CharField(blank=True, max_length=20000)),
                ('integrated_at', models.DateTimeField(auto_now=True)),
                ('integrated_by_name', models.CharField(editable=False, max_length=150)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.collection')),
                ('integrated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.project'),
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together={('qgis_layer_id', 'project')},
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=1000)),
                ('is_primary_key', models.BooleanField(default=False)),
                ('type_wfs', models.CharField(max_length=1000)),
                ('type_oapif', models.CharField(max_length=1000)),
                ('type_oapif_format', models.CharField(max_length=1000)),
                ('alias', models.CharField(max_length=1000)),
                ('comment', models.CharField(max_length=1000)),
                ('nullable', models.BooleanField(default=True)),
                ('length', models.IntegerField(null=True)),
                ('precision', models.IntegerField(null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.vector')),
            ],
            options={
                'verbose_name': 'field',
                'verbose_name_plural': 'fields',
                'unique_together': {('name', 'dataset')},
            },
        ),
    ]
