# Generated by Django 6.0.6 on 2026-07-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='styles',
            field=models.JSONField(default=list, help_text='Rendered style definitions associated with this datasource.'),
        ),
    ]
