# Generated by Django 6.0.6 on 2026-06-18 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fence_geometry_alter_fence_id_alter_fence_name_and_more'),
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='integrated_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='integrated_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='integrated_by_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='version',
        ),
        migrations.AddField(
            model_name='project',
            name='qgis_version',
            field=models.CharField(blank=True, help_text='QGIS version the project was created with.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identifier of the collection.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(help_text='Unique name of the collection.', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Organisation that owns this collection.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organisation'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='bbox',
            field=models.CharField(help_text='Bounding box of the dataset in the source coordinate reference system.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='bbox_wgs84',
            field=models.CharField(help_text='Bounding box of the dataset transformed to WGS84.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='crs',
            field=models.JSONField(default=dict, help_text='Coordinate reference system of the dataset.'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='driver',
            field=models.CharField(help_text='Provider driver name used to access the dataset.', max_length=50),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identifier of the dataset.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='maximum_scale',
            field=models.FloatField(help_text='Maximum scale at which the dataset is visible.', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='minimum_scale',
            field=models.FloatField(help_text='Minimum scale at which the dataset is visible.', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(help_text='Name of the dataset.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='project',
            field=models.ForeignKey(help_text='Project the dataset belongs to.', on_delete=django.db.models.deletion.CASCADE, to='integration.project'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='qgis_layer_id',
            field=models.CharField(help_text='Layer identifier from the source QGIS project.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='source',
            field=models.JSONField(default=dict, help_text='Source configuration and connection metadata of the dataset.'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='styles',
            field=models.JSONField(default=dict, help_text='Rendered style definitions associated with this dataset.'),
        ),
        migrations.AlterField(
            model_name='field',
            name='alias',
            field=models.CharField(help_text='Human-readable field label.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='field',
            name='comment',
            field=models.CharField(help_text='Comment or description of the field.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='field',
            name='dataset',
            field=models.ForeignKey(help_text='Vector dataset this field belongs to.', on_delete=django.db.models.deletion.CASCADE, to='integration.vector'),
        ),
        migrations.AlterField(
            model_name='field',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identifier of the field.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='field',
            name='is_primary_key',
            field=models.BooleanField(default=False, help_text='Whether this field is the dataset primary key.'),
        ),
        migrations.AlterField(
            model_name='field',
            name='length',
            field=models.IntegerField(help_text='....', null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(help_text='Original field name from the source dataset.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='field',
            name='nullable',
            field=models.BooleanField(default=True, help_text='Whether this field can store null values.'),
        ),
        migrations.AlterField(
            model_name='field',
            name='precision',
            field=models.IntegerField(help_text='Numeric precision.', null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(help_text='Original data type from the source dataset.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='field',
            name='type_oapif',
            field=models.CharField(help_text='Field datatype exposed through OGC API Features.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='field',
            name='type_oapif_format',
            field=models.CharField(help_text='Output format for the OGC API Features field type.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='field',
            name='type_wfs',
            field=models.CharField(help_text='Field datatype exposed through WFS.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='collection',
            field=models.ForeignKey(help_text='Collection this project belongs to actually.', on_delete=django.db.models.deletion.CASCADE, to='integration.collection'),
        ),
        migrations.AlterField(
            model_name='project',
            name='hash',
            field=models.CharField(blank=True, help_text='Hash used to detect changes in project content.', max_length=20000),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identifier of the project.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Name of the project.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vector',
            name='geometry_type_simple',
            field=models.CharField(help_text='Simplified geometry type of the vector dataset (eg. point, line, polygon).', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vector',
            name='geometry_type_wkb',
            field=models.CharField(help_text='Geometry type of the vector dataset.', max_length=1000),
        ),
    ]
