"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

from georama.core.auth import get_authentication_methods_middlewares

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-n*xqzi(i)c&4cl52a_3+^mr19o+om6u)&d(cuz1ibrvm*t)9s!"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

LOGGING = {
    "version": 1,  # the dictConfig format version
    "disable_existing_loggers": False,  # retain the default loggers
}

GEORAMA_ALLOWED_HOSTS = os.environ.get("GEORAMA_ALLOWED_HOSTS", "").split(" ")

ALLOWED_HOSTS = [] + GEORAMA_ALLOWED_HOSTS

if bool(os.environ.get("GEORAMA_SECURE_PROXY_SSL_HEADER", False)):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

SHARED_APPS = (
    'django_tenants',  # mandatory
    'mandants.apps.MandantsConfig',

    'django.contrib.contenttypes',

    # everything below here is optional
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.admin',

    # added by DDDPT
    "jazzmin",
    "django.contrib.staticfiles",
    # apps by webgis
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "adminsortable2",
    "treebeard",
    "django_extensions",
)

TENANT_APPS = (
    # your tenant-specific apps
    "georama.core.apps.CoreConfig",
    "georama.features.apps.VectorparrotConfig",
    "georama.maps.apps.RasteroctopusConfig",
    "georama.data_integration.apps.QmeleonConfig",
    "corsheaders",
    "georama.webgis.apps.ClogsConfig",
)

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]


GEORAMA_AUTHENTICATION_METHODS = os.environ.get(
    "GEORAMA_AUTHENTICATION_METHODS", "DJANGO_CONTRIB_AUTH"
).split(" ")

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    *get_authentication_methods_middlewares(GEORAMA_AUTHENTICATION_METHODS),
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # webgis
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "georama.core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "georama.core.wsgi.application"

CSRF_TRUSTED_ORIGINS = [] + os.getenv(
    "GEORAMA_CSRF_TRUSTED_ORIGINS", "http://localhost:8080"
).split(" ")

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        # "ENGINE": "django.db.backends.postgresql",
        'ENGINE': 'django_tenants.postgresql_backend',
        "HOST": os.environ.get("GEORAMA_DB_HOST", "localhost"),
        "PORT": os.environ.get("GEORAMA_DB_PORT", "54321"),
        "USER": os.environ.get("GEORAMA_DB_USER", "postgres"),
        "PASSWORD": os.environ.get("GEORAMA_DB_PW", "test"),
        "NAME": os.environ.get("GEORAMA_DB_NAME", "postgres"),
    }
}

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

CORS_ALLOWED_ORIGINS = [] + os.getenv(
    "GEORAMA_CORS_ALLOWED_ORIGINS", "https://localhost:8443"
).split(" ")

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

APPEND_SLASH = False


TENANT_MODEL = "mandants.Client"  # app.Model
TENANT_DOMAIN_MODEL = "mandants.Domain"  # app.Model