"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from pathlib import Path

from georama.core.auth import get_authentication_methods_middlewares

from configurations import Configuration, values


class Base(Configuration):
    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    BASE_DIR = Path(__file__).resolve().parent

    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = values.SecretValue()

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = values.BooleanValue(False, environ_prefix="GEORAMA")

    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "{levelname} {asctime} {module} {message}",
                "style": "{",
            },
            "simple": {
                "format": "{levelname} {message}",
                "style": "{",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "verbose",
            },
        },
        "root": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
        "loggers": {
            "core": {
                "handlers": ["console"],
                "level": "DEBUG",
                "propagate": False,
            },
            "data_integration": {
                "handlers": ["console"],
                "level": "DEBUG",
                "propagate": False,
            },
            "features": {
                "handlers": ["console"],
                "level": "DEBUG",
                "propagate": False,
            },
            "maps": {
                "handlers": ["console"],
                "level": "DEBUG",
                "propagate": False,
            },
            "webgis": {
                "handlers": ["console"],
                "level": "DEBUG",
                "propagate": False,
            },
        },
    }

    ALLOWED_HOSTS = values.ListValue([], separator=' ', environ_prefix="GEORAMA")

    # Proxy "X-Forwarded-..." headers
    # https://docs.djangoproject.com/en/5.2/ref/settings/#secure-proxy-ssl-header

    GEORAMA_SECURE_PROXY_SSL_HEADER = values.BooleanValue(False, environ_prefix=None)

    @property
    def SECURE_PROXY_SSL_HEADER(self):
        if self.GEORAMA_SECURE_PROXY_SSL_HEADER:
            return ("HTTP_X_FORWARDED_PROTO", "https")

    # Application definition

    INSTALLED_APPS = [
        "jazzmin",
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        "georama.core.apps.CoreConfig",
        "georama.features.apps.FeaturesConfig",
        "georama.maps.apps.MapsConfig",
        "georama.data_integration.apps.DataintegrationConfig",
        # apps by webgis
        "corsheaders",
        "georama.webgis.apps.WebgisConfig",
        "allauth",
        "allauth.account",
        "allauth.socialaccount",
        "adminsortable2",
        "treebeard",
        "django_extensions",
    ]

    GEORAMA_AUTHENTICATION_METHODS = values.ListValue(
        ["DJANGO_CONTRIB_AUTH"], separator=' ', environ_prefix=None,
    )

    @property
    def MIDDLEWARE(self):
        return [
            "django.middleware.security.SecurityMiddleware",
            "django.contrib.sessions.middleware.SessionMiddleware",
            "corsheaders.middleware.CorsMiddleware",
            "django.middleware.common.CommonMiddleware",
            # "django.middleware.csrf.CsrfViewMiddleware",
            "django.contrib.auth.middleware.AuthenticationMiddleware",
            *get_authentication_methods_middlewares(self.GEORAMA_AUTHENTICATION_METHODS),
            "django.contrib.messages.middleware.MessageMiddleware",
            "django.middleware.clickjacking.XFrameOptionsMiddleware",
            # webgis
            "allauth.account.middleware.AccountMiddleware",
        ]

    ROOT_URLCONF = "georama.core.urls"

    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [],
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.debug",
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                ],
            },
        },
    ]

    WSGI_APPLICATION = "georama.core.wsgi.application"

    CSRF_TRUSTED_ORIGINS = values.ListValue(
        ["http://localhost:4242"], separator=' ', environ_prefix="GEORAMA",
    )

    # Database
    # https://docs.djangoproject.com/en/5.0/ref/settings/#databases

    DB_NAME = values.Value("postgres", environ_prefix="GEORAMA")
    DB_ENGINE = values.Value("django.db.backends.postgresql", environ_prefix="GEORAMA")
    DB_USER = values.Value("postgres", environ_prefix="GEORAMA")
    DB_PW = values.Value("test", environ_prefix="GEORAMA")
    DB_HOST = values.Value("localhost", environ_prefix="GEORAMA")
    DB_PORT = values.Value("54321", environ_prefix="GEORAMA")
    DB_OPTIONS = values.DictValue({}, environ_prefix="GEORAMA")

    @property
    def DATABASES(self):
        return {
            "default": {
                "ENGINE": self.DB_ENGINE,
                "NAME": self.DB_NAME,
                "USER": self.DB_USER,
                "PASSWORD": self.DB_PW,
                "HOST": self.DB_HOST,
                "PORT": self.DB_PORT,
                "OPTIONS": self.DB_OPTIONS,
            }
        }

    # Password validation
    # https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]

    CORS_ALLOWED_ORIGINS = values.ListValue(
        ["https://localhost:9309"], separator=' ', environ_prefix="GEORAMA",
    )
    CORS_ALLOW_CREDENTIALS = values.BooleanValue(
        False, environ_prefix="GEORAMA",
    )

    # Internationalization
    # https://docs.djangoproject.com/en/5.0/topics/i18n/

    LANGUAGE_CODE = "en-us"

    TIME_ZONE = "UTC"

    USE_I18N = True

    USE_TZ = True

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/5.0/howto/static-files/

    STATIC_URL = "static/"
    STATIC_ROOT = BASE_DIR / "static"

    # Default primary key field type
    # https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

    DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

    APPEND_SLASH = False


class Dev(Base):
    SECRET_KEY = "django-insecure-n*xqzi(i)c&4cl52a_3+^mr19o+om6u)&d(cuz1ibrvm*t)9s!"

    DEBUG = values.BooleanValue(True, environ_prefix="GEORAMA")


class Prod(Base):
    SECRET_KEY = values.SecretValue()

    DEBUG = values.BooleanValue(False, environ_prefix="GEORAMA")
