# Generated by Django 5.0.6 on 2024-09-06 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qmeleon', '0013_customdataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedAsWms',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('public', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('license', models.TextField(default='\n    This dataset is made available under the Open Database\n    License: http://opendatacommons.org/licenses/odbl/1.0/.\n    Any rights in individual contents of the database are licensed\n    under the Database Contents\n    License: http://opendatacommons.org/licenses/dbcl/1.0/\n    ')),
                ('fees', models.TextField(default='No fees apply.')),
                ('access_constraints', models.TextField(default='No access constraints apply.')),
                ('custom_dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_ogc_wms', related_query_name='published_ogc_wms', to='qmeleon.customdataset')),
                ('raster_dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_ogc_wms', related_query_name='published_ogc_wms', to='qmeleon.rasterdataset')),
                ('vector_dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_ogc_wms', related_query_name='published_ogc_wms', to='qmeleon.vectordataset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
