# Generated by Django 5.0.6 on 2024-08-08 11:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedAsWms',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public', models.BooleanField(default=True)),
                ('project', models.CharField(max_length=1000, unique=True)),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('license', models.TextField(default='\n    This dataset is made available under the Open Database\n    License: http://opendatacommons.org/licenses/odbl/1.0/.\n    Any rights in individual contents of the database are licensed\n    under the Database Contents\n    License: http://opendatacommons.org/licenses/dbcl/1.0/\n    ')),
                ('fees', models.TextField(default='No fees apply.')),
                ('access_constraints', models.TextField(default='No access constraints apply.')),
                ('srs', models.JSONField(default=list)),
                ('style', models.URLField()),
                ('queryable', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
