# Generated by Django 5.0.6 on 2024-12-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasteroctopus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedaswms',
            name='extent_buffer',
            field=models.FloatField(default=0.0),
        ),
    ]
