# Generated by Django 5.0.6 on 2024-08-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasteroctopus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedaswms',
            name='name',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='publishedaswms',
            name='project',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='publishedaswms',
            unique_together={('name', 'project')},
        ),
    ]
