# Generated by Django 5.0.6 on 2024-08-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasteroctopus', '0002_alter_publishedaswms_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publishedaswms',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='publishedaswms',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='publishedaswms',
            name='project',
            field=models.CharField(max_length=1000),
        ),
    ]
