# Generated by Django 5.0.6 on 2024-08-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasteroctopus', '0003_alter_publishedaswms_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedaswms',
            name='project',
        ),
        migrations.RemoveField(
            model_name='publishedaswms',
            name='srs',
        ),
        migrations.AlterField(
            model_name='publishedaswms',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='publishedaswms',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
