# Generated by Django 5.0.6 on 2024-08-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasteroctopus', '0004_remove_publishedaswms_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedaswms',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publishedaswms',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='publishedaswms',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
