# Generated by Django 5.0.6 on 2024-08-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasteroctopus', '0005_alter_publishedaswms_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedaswms',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
