# Generated by Django 5.0.6 on 2024-08-26 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmeleon', '0009_alter_rasterdataset_name_alter_vectordataset_name'),
        ('rasteroctopus', '0006_alter_publishedaswms_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedaswms',
            name='queryable',
        ),
        migrations.RemoveField(
            model_name='publishedaswms',
            name='style',
        ),
        migrations.AddField(
            model_name='publishedaswms',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_ogc_wms', related_query_name='published_ogc_wms', to='qmeleon.rasterdataset'),
        ),
    ]
