# Generated by Django 5.2.10 on 2026-02-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfield_link", "0002_add_app_permission"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QfieldCloudProject",
        ),
    ]
