# Generated by Django 6.0.6 on 2026-06-24 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_use_manage_api', 'Can use the management API')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FeatureLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identifier of the feature layer.', primary_key=True, serialize=False)),
                ('datasource', models.ForeignKey(help_text='Datasource the feature layer points to.', on_delete=django.db.models.deletion.CASCADE, related_name='feature_layers', related_query_name='feature_layer', to='integration.vector')),
            ],
            options={
                'verbose_name': 'feature layer',
                'verbose_name_plural': 'feature layers',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identifier of the field.', primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('visible', models.BooleanField(default=False)),
                ('datasource_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_layer_fields', related_query_name='feature_layer_field', to='integration.field')),
                ('feature_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', related_query_name='field', to='features.featurelayer')),
            ],
            options={
                'verbose_name': 'field',
                'verbose_name_plural': 'fields',
                'unique_together': {('feature_layer', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identifier of the metadata.', primary_key=True, serialize=False)),
                ('default_items', models.IntegerField(default=10, null=True)),
                ('max_items', models.IntegerField(default=500, null=True)),
                ('on_exceed', models.CharField(choices=[('ERROR', 'error'), ('THROTTLE', 'throttle')], default='ERROR', max_length=10, null=True)),
                ('feature_layer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='features.featurelayer')),
            ],
            options={
                'verbose_name': 'metadata',
                'verbose_name_plural': 'metadata',
            },
        ),
        migrations.CreateModel(
            name='FeatureLayerGroupObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='features.featurelayer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'abstract': False,
                'unique_together': {('group', 'permission', 'content_object')},
            },
        ),
        migrations.CreateModel(
            name='FeatureLayerUserObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='features.featurelayer')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'permission', 'content_object')},
            },
        ),
        migrations.CreateModel(
            name='FieldGroupObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='features.field')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'abstract': False,
                'unique_together': {('group', 'permission', 'content_object')},
            },
        ),
        migrations.CreateModel(
            name='FieldUserObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='features.field')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'permission', 'content_object')},
            },
        ),
    ]
