# Generated by Django 6.0.6 on 2026-07-15 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identifier of the metadata.', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', help_text='The verbose title of the connected item.', max_length=1000)),
                ('description', models.TextField(blank=True, default='')),
                ('license', models.TextField(default='\n    This dataset is made available under the Open Database\n    License: http://opendatacommons.org/licenses/odbl/1.0/.\n    Any rights in individual contents of the database are licensed\n    under the Database Contents\n    License: http://opendatacommons.org/licenses/dbcl/1.0/\n    ')),
                ('fees', models.TextField(default='No fees apply.')),
                ('access_constraints', models.TextField(default='No access constraints apply.')),
            ],
            options={
                'verbose_name': 'metadata',
                'verbose_name_plural': 'metadata',
            },
        ),
        migrations.CreateModel(
            name='FeatureLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identifier of the feature layer.', primary_key=True, serialize=False)),
                ('public', models.BooleanField(default=False)),
                ('default_items', models.IntegerField(default=10, help_text='The default number of features that should be returned for the layer.', null=True)),
                ('max_items', models.IntegerField(default=500, help_text='The maximum number of features that may be returned for the layer.', null=True)),
                ('on_exceed', models.CharField(choices=[('ERROR', 'error'), ('THROTTLE', 'throttle')], default='ERROR', help_text='Whether the server should return an error or cap the value when more thanmax_items are requested', max_length=10, null=True)),
                ('datasource', models.ForeignKey(help_text='Datasource the feature layer points to.', on_delete=django.db.models.deletion.CASCADE, related_name='feature_layers', related_query_name='feature_layer', to='integration.vector')),
                ('metadata', models.OneToOneField(help_text='Metadata of the feature layer.', on_delete=django.db.models.deletion.CASCADE, related_name='feature_layer', to='features.metadata')),
            ],
            options={
                'verbose_name': 'feature layer',
                'verbose_name_plural': 'feature layers',
                'permissions': [('manage_object_permissions', 'Can manage object permissions'), ('view_objects_on_published_layer', 'Can view items on published layer'), ('create_objects_on_published_layer', 'Can create items on published layer'), ('delete_objects_on_published_layer', 'Can delete items on published layer'), ('update_objects_on_published_layer', 'Can update items on published layer')],
            },
        ),
        migrations.CreateModel(
            name='FeatureLayerGroupObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='features.featurelayer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'abstract': False,
                'unique_together': {('group', 'permission', 'content_object')},
            },
        ),
        migrations.CreateModel(
            name='FeatureLayerUserObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='features.featurelayer')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'permission', 'content_object')},
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identifier of the field.', primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('visible', models.BooleanField(default=True)),
                ('datasource_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_layer_fields', related_query_name='feature_layer_field', to='integration.vectorfield')),
                ('feature_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', related_query_name='field', to='features.featurelayer')),
            ],
            options={
                'verbose_name': 'field',
                'verbose_name_plural': 'fields',
                'unique_together': {('feature_layer', 'name')},
            },
        ),
    ]
