# Generated by Django 5.0.6 on 2025-05-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedasogcapifeatures",
            name="default_items",
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name="publishedasogcapifeatures",
            name="max_items",
            field=models.IntegerField(default=500, null=True),
        ),
        migrations.AddField(
            model_name="publishedasogcapifeatures",
            name="on_exceed",
            field=models.CharField(
                choices=[("ERROR", "error"), ("THROTTLE", "throttle")],
                default="ERROR",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="publishedaswfs",
            name="default_items",
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name="publishedaswfs",
            name="max_items",
            field=models.IntegerField(default=500, null=True),
        ),
        migrations.AddField(
            model_name="publishedaswfs",
            name="on_exceed",
            field=models.CharField(
                choices=[("ERROR", "error"), ("THROTTLE", "throttle")],
                default="ERROR",
                max_length=10,
                null=True,
            ),
        ),
    ]
