# Generated by Django 5.2.10 on 2026-02-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0004_alter_columnogcapifeatures_dataset_column"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publishedasogcapifeatures",
            options={
                "permissions": [
                    ("can_manage_object_permissions", "Can manage object permissions")
                ]
            },
        ),
    ]
