# Generated by Django 5.2.10 on 2026-03-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0005_alter_publishedasogcapifeatures_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="columnogcapifeatures",
            options={"verbose_name": "OAPIF Column", "verbose_name_plural": "OAPIF Columns"},
        ),
        migrations.AlterModelOptions(
            name="publishedasogcapifeatures",
            options={
                "permissions": [
                    ("can_manage_object_permissions", "Can manage object permissions")
                ],
                "verbose_name": "OAPIF Layer",
                "verbose_name_plural": "OAPIF Layers",
            },
        ),
    ]
