# Generated by Django 5.2.14 on 2026-06-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_alter_columnogcapifeatures_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnogcapifeatures',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='columnwfs',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
