# Generated by Django 5.2.10 on 2026-04-23 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_integration", "0033_remove_path_field_from_dataset"),
        ("process", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publishedasdataset",
            options={"verbose_name": "Dataset", "verbose_name_plural": "Datasets"},
        ),
        migrations.AddField(
            model_name="publishedasdataset",
            name="custom_dataset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="published_oapip_dataset",
                related_query_name="published_oapip_dataset",
                to="data_integration.customdataset",
            ),
        ),
        migrations.AddField(
            model_name="publishedasdataset",
            name="raster_dataset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="published_oapip_dataset",
                related_query_name="published_oapip_dataset",
                to="data_integration.rasterdataset",
            ),
        ),
        migrations.AddField(
            model_name="publishedasdataset",
            name="vector_dataset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="published_oapip_dataset",
                related_query_name="published_oapip_dataset",
                to="data_integration.vectordataset",
            ),
        ),
    ]
