# Generated by Django 5.2.10 on 2026-04-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0002_alter_publishedasdataset_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publishedasdataset",
            options={
                "permissions": [
                    ("can_manage_object_permissions", "Can manage object permissions")
                ],
                "verbose_name": "Dataset",
                "verbose_name_plural": "Datasets",
            },
        ),
    ]
