"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import copy
from pathlib import Path

from configurations import Configuration, values
from corsheaders.defaults import default_headers
from django.utils.translation import gettext_lazy as _

LIST_ENV_SEPARATOR = " "
GEORAMA_ENV_PREFIX = "GEORAMA"


class Base(Configuration):
    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    BASE_DIR = Path(__file__).resolve().parent.parent.parent
    STATIC_ROOT = values.Value(BASE_DIR / ".static", environ_prefix=GEORAMA_ENV_PREFIX)

    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = values.SecretValue()

    # https://docs.djangoproject.com/en/6.0/ref/settings/#std-setting-ALLOWED_HOSTS
    ALLOWED_HOSTS = values.ListValue([], separator=LIST_ENV_SEPARATOR)

    # https://docs.djangoproject.com/en/6.0/ref/settings/#std-setting-CSRF_TRUSTED_ORIGINS
    CSRF_TRUSTED_ORIGINS = values.ListValue(
        ["http://localhost:4242"],
        separator=LIST_ENV_SEPARATOR,
    )

    # https://github.com/adamchainz/django-cors-headers#cors_allowed_origins-sequencestr
    CORS_ALLOWED_ORIGINS = values.ListValue(
        ["https://localhost:9309"],
        separator=LIST_ENV_SEPARATOR,
        environ_prefix=GEORAMA_ENV_PREFIX,
    )
    CORS_ALLOW_CREDENTIALS = values.BooleanValue(
        True,
        environ_prefix=GEORAMA_ENV_PREFIX,
    )
    CORS_ALLOW_METHODS = values.ListValue(
        [
            "DELETE",
            "HEAD",
            "GET",
            "OPTIONS",
            "PATCH",
            "POST",
            "PUT",
        ],
        separator=LIST_ENV_SEPARATOR,
        environ_prefix=GEORAMA_ENV_PREFIX,
    )
    CORS_ALLOW_HEADERS = values.ListValue(
        [
            *default_headers,
            "content-crs",
        ],
        separator=LIST_ENV_SEPARATOR,
        environ_prefix=GEORAMA_ENV_PREFIX,
    )

    # Proxy "X-Forwarded-..." headers
    # https://docs.djangoproject.com/en/6.0/ref/settings/#secure-proxy-ssl-header
    SECURE_PROXY_SSL_HEADER = values.TupleValue(None)

    DEBUG = False

    # Django logging settings
    # See https://docs.djangoproject.com/en/6.0/topics/logging/
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "{levelname} {asctime} {module} {message}",
                "style": "{",
            },
            "simple": {
                "format": "{levelname} {message}",
                "style": "{",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "verbose",
            },
        },
        "root": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
        "loggers": {
            "core": {
                "handlers": ["console"],
                "level": "DEBUG",
                "propagate": False,
            },
            "data_integration": {
                "handlers": ["console"],
                "level": "DEBUG",
                "propagate": False,
            },
            "features": {
                "handlers": ["console"],
                "level": "DEBUG",
                "propagate": False,
            },
            "maps": {
                "handlers": ["console"],
                "level": "DEBUG",
                "propagate": False,
            },
            "webgis": {
                "handlers": ["console"],
                "level": "DEBUG",
                "propagate": False,
            },
        },
    }

    # Application definition

    AUTH_USER_MODEL = "core.GeoramaUser"

    INSTALLED_APPS = [
        "unfold",  # before django.contrib.admin
        "unfold.contrib.filters",  # optional, if special filters are needed
        "unfold.contrib.forms",  # optional, if special form elements are needed
        "unfold.contrib.inlines",  # optional, if special inlines are needed
        "unfold.contrib.import_export",
        # optional, if django-import-export package is used
        "unfold.contrib.guardian",  # optional, if django-guardian package is used
        "unfold.contrib.simple_history",
        # optional, if django-simple-history package is used
        "unfold.contrib.location_field",
        # optional, if django-location-field package is used
        "unfold.contrib.constance",  # optional, if django-constance package is used
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        "django.contrib.gis",
        "rest_framework",
        "rest_framework_gis",
        "drf_spectacular",
        "drf_spectacular_sidecar",
        "django_filters",
        "formset",  # https://github.com/jrief/django-formset
        "guardian",
        "georama.core.apps.CoreConfig",
        "georama.integration.apps.IntegrationConfig",
        "georama.features.apps.FeaturesConfig",
        "allauth",
        "allauth.account",
        "allauth.socialaccount",
        "allauth.socialaccount.providers.openid_connect",
    ]

    MIDDLEWARE = [
        "django.middleware.security.SecurityMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "corsheaders.middleware.CorsMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.locale.LocaleMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
        "allauth.account.middleware.AccountMiddleware",
        "georama.core.middleware.organisation.OrganisationMiddleware",
    ]

    AUTHENTICATION_BACKENDS = (
        "django.contrib.auth.backends.ModelBackend",  # this is default
        "guardian.backends.ObjectPermissionBackend",
    )

    # Django allauth's social account configuration
    # https://docs.allauth.org/en/dev/socialaccount/configuration.html
    SOCIALACCOUNT_QUERY_EMAIL = True
    SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
    SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
    SOCIALACCOUNT_LOGIN_ON_GET = True

    OIDC_NAME = values.Value("Keycloak", environ_prefix="GEORAMA")
    OIDC_SERVER_URL = values.Value(environ_prefix="GEORAMA")
    OIDC_CLIENT_ID = values.Value("georama-oidc", environ_prefix="GEORAMA")
    OIDC_OAUTH_PKCE_ENABLED = values.BooleanValue(True, environ_prefix="GEORAMA")
    OIDC_SECRET = values.Value("secret", environ_prefix="GEORAMA")
    OIDC_PROVIDER_ID = values.Value("keycloak", environ_prefix="GEORAMA")

    @property
    def SOCIALACCOUNT_PROVIDERS(self):
        return {
            "openid_connect": {
                "OAUTH_PKCE_ENABLED": self.OIDC_OAUTH_PKCE_ENABLED,
                "APP": {
                    "provider_id": self.OIDC_PROVIDER_ID,
                    "name": self.OIDC_NAME,
                    "client_id": self.OIDC_CLIENT_ID,
                    "secret": self.OIDC_SECRET,
                    "settings": {
                        "server_url": self.OIDC_SERVER_URL,
                    },
                },
            },
        }

    ROOT_URLCONF = "georama.urls"

    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [],
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.debug",
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                    "georama.core.context_processors.menu_items",
                ],
            },
        },
    ]

    ASGI_APPLICATION = "georama.asgi.application"

    # Database
    # https://docs.djangoproject.com/en/6.0/ref/settings/#databases

    DB_NAME = values.Value(environ_prefix=GEORAMA_ENV_PREFIX)
    DB_ENGINE = values.Value(
        "django.contrib.gis.db.backends.postgis", environ_prefix=GEORAMA_ENV_PREFIX
    )
    DB_USER = values.Value(environ_prefix=GEORAMA_ENV_PREFIX)
    DB_PW = values.Value(environ_prefix=GEORAMA_ENV_PREFIX)
    DB_HOST = values.Value(environ_prefix=GEORAMA_ENV_PREFIX)
    DB_PORT = values.Value(environ_prefix=GEORAMA_ENV_PREFIX)
    DB_OPTIONS = values.DictValue(
        {
            "pool": True,
        },
        environ_prefix=GEORAMA_ENV_PREFIX,
    )

    @property
    def DATABASES(self):
        return {
            "default": {
                "ENGINE": self.DB_ENGINE,
                "NAME": self.DB_NAME,
                "USER": self.DB_USER,
                "PASSWORD": self.DB_PW,
                "HOST": self.DB_HOST,
                "PORT": self.DB_PORT,
                "OPTIONS": self.DB_OPTIONS,
            },
        }

    # Password validation
    # https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]

    PASSWORD_HASHERS = [
        "django.contrib.auth.hashers.Argon2PasswordHasher",
        "django.contrib.auth.hashers.PBKDF2PasswordHasher",
        "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
        "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
        "django.contrib.auth.hashers.ScryptPasswordHasher",
        "django.contrib.auth.hashers.MD5PasswordHasher",
    ]

    # Internationalization
    # https://docs.djangoproject.com/en/6.0/topics/i18n/

    LANGUAGE_CODE = "en-us"

    TIME_ZONE = "UTC"

    USE_I18N = True

    USE_TZ = True

    LANGUAGES = [
        ("en", _("English")),
        ("de", _("German")),
    ]

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/6.0/howto/static-files/
    STATIC_URL = "static/"

    APPEND_SLASH = False

    # Default primary key field type
    # https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
    DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
    ########
    # Unfold => https://unfoldadmin.com/docs/
    ########
    UNFOLD = {
        "SITE_HEADER": "ADMIN",
        "SIDEBAR": {
            "show_search": False,
        },
    }
    ##########
    # Guardian => https://django-guardian.readthedocs.io
    ##########
    GUARDIAN_MONKEY_PATCH_USER = False
    GUARDIAN_MONKEY_PATCH_GROUP = False

    ######################
    # Django Restframework => https://www.django-rest-framework.org/api-guide/settings/
    ######################
    REST_FRAMEWORK = {
        "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
        "PAGE_SIZE": 10,
        "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
        "DEFAULT_FILTER_BACKENDS": [
            "django_filters.rest_framework.DjangoFilterBackend",
        ],
        "DEFAULT_RENDERER_CLASSES": [
            "rest_framework.renderers.JSONRenderer",
            "rest_framework.renderers.BrowsableAPIRenderer",
        ],
        "URL_FORMAT_OVERRIDE": "f",
    }

    LOGIN_REDIRECT_URL = "core:index"

    ###########################
    # Georama specific settings
    ###########################

    QGIS_EXPORTER_UNIFY_LAYER_NAMES_BY_GROUP = values.BooleanValue(
        True, environ_prefix=GEORAMA_ENV_PREFIX
    )
    WEBGISURL = values.Value(environ_prefix=GEORAMA_ENV_PREFIX)
    SITE_TITLE = values.Value("Georama", environ_prefix=GEORAMA_ENV_PREFIX)

    # the domain georama runs-this is be used for deriving the organisation
    # if georama runs already below a subdomain, you need to include it in this setting
    # e.g. sub.example.com or sub.sub.example.com
    ORGANISATION_DOMAIN = values.Value(environ_prefix=GEORAMA_ENV_PREFIX)
    # Allow public access on the global application or not
    ORGANISATION_GLOBAL_PUBLIC_ACCESS = values.BooleanValue(True, environ_prefix=GEORAMA_ENV_PREFIX)
    # view name which should be used to redirect to, when someone tries to
    # access nonpublic organisation unauthenticated
    ORGANISATION_NOT_AUTHENTICATED_TARGET = values.Value(
        "core:login", environ_prefix=GEORAMA_ENV_PREFIX
    )
    # view names which should be accessable without middleware handling
    # use this with CAUTION because it might expose data unwanted!
    ORGANISATION_GLOBAL_PUBLIC_ACCESS_BYPASS_TARGETS = values.ListValue(
        [],
        environ_prefix=GEORAMA_ENV_PREFIX,
        separator=LIST_ENV_SEPARATOR,
    )


class Dev(Base):
    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = True
    SECRET_KEY = "django-insecure-62uf==xpvgw)y-s#+0g8w4vorazvp3k8_-zewl829h-49^#1#8"

    TEMPLATES = copy.deepcopy(Base.TEMPLATES)

    TEMPLATES[0]["OPTIONS"]["loaders"] = [
        "django.template.loaders.filesystem.Loader",
        "django.template.loaders.app_directories.Loader",
    ]
    TEMPLATES[0]["OPTIONS"]["context_processors"] += [
        "django.template.context_processors.request",
    ]
    del TEMPLATES[0]["APP_DIRS"]

    # https://docs.djangoproject.com/en/6.0/ref/settings/#std-setting-ALLOWED_HOSTS
    ALLOWED_HOSTS = values.ListValue(
        [
            ".localhost",
            # convenience hostnames used by developers can be added here
            "georama.local",
        ],
        separator=LIST_ENV_SEPARATOR,
        environ_prefix=GEORAMA_ENV_PREFIX,
    )

    # https://docs.djangoproject.com/en/6.0/ref/settings/#std-setting-CSRF_TRUSTED_ORIGINS
    CSRF_TRUSTED_ORIGINS = values.ListValue(
        [
            "http://localhost:4242",
            "https://localhost:9309",  # GG (from georama stack)
            "http://localhost:9308",  # GG (from georama stack)
            "https://app.localhost:8080",  # GG (standalone)
            "https://localhost:8080",  # GG (standalone)
            # convenience GG hostnames used by developers can be added here
            "http://geogirafe.local",
        ],
        separator=LIST_ENV_SEPARATOR,
    )

    # https://github.com/adamchainz/django-cors-headers#cors_allowed_origins-sequencestr
    CORS_ALLOWED_ORIGINS = values.ListValue(
        [
            "https://localhost:9309",  # GG (from georama stack)
            "http://localhost:9308",  # GG (from georama stack)
            "https://app.localhost:8080",  # GG (standalone)
            "https://localhost:8080",  # GG (standalone)
            # convenience GG hostnames used by developers can be added here
            "http://geogirafe.local",
        ],
        separator=LIST_ENV_SEPARATOR,
    )

    INSTALLED_APPS = Base.INSTALLED_APPS + [
        "silk",
        "django_extensions",
    ]

    MIDDLEWARE = Base.MIDDLEWARE + [
        "silk.middleware.SilkyMiddleware",
    ]

    GEORAMA_AUTHENTICATION_METHODS = values.ListValue(
        ["BASIC_HTTP"],
        separator=LIST_ENV_SEPARATOR,
        environ_prefix=None,
    )

    ORGANISATION_DOMAIN = "localhost"


class Prod(Base):
    pass


class Test(Base):
    SECRET_KEY = "django-testing-secret-key"

    @property
    def DATABASES(self):
        db_settings = super().DATABASES
        db_settings["default"]["NAME"] = "test"
        return db_settings

    PASSWORD_HASHERS = [
        "django.contrib.auth.hashers.MD5PasswordHasher",
    ]
    ALLOWED_HOSTS = Dev.ALLOWED_HOSTS
    ORGANISATION_DOMAIN = Dev.ORGANISATION_DOMAIN
