# Generated by Django 6.0.6 on 2026-06-25 10:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import guardian.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identifier of the organisation.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the organisation.')),
                ('domain', models.CharField(help_text='Domain used to identify the organisation.', unique=True)),
                ('public_access', models.BooleanField(default=False, help_text='Whether anonymous users can access this organisation.')),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
            },
        ),
        migrations.CreateModel(
            name='GeoramaUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identifier of the user.', primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=(models.Model, guardian.mixins.GuardianUserMixin),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Fence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identifier of the fence.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the fence.')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Geographic boundary of the fence.', srid=4326)),
                ('organisation', models.ForeignKey(blank=True, help_text='Organisation the fence belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fences', to='core.organisation')),
            ],
            options={
                'verbose_name': 'fence',
                'verbose_name_plural': 'fences',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identifier of the membership.', primary_key=True, serialize=False)),
                ('user', models.ForeignKey(help_text='User associated with the membership.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, help_text='Organisation associated with the membership.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.organisation')),
            ],
            options={
                'verbose_name': 'membership',
                'verbose_name_plural': 'memberships',
                'unique_together': {('organisation', 'user')},
            },
        ),
    ]
