# Generated by Django 6.0.6 on 2026-06-18 12:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fence',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Geographic boundary of the fence.', srid=4326),
        ),
        migrations.AlterField(
            model_name='fence',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identifier of the fence.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fence',
            name='name',
            field=models.CharField(help_text='Name of the fence.'),
        ),
        migrations.AlterField(
            model_name='fence',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Organisation the fence belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fences', to='core.organisation'),
        ),
        migrations.AlterField(
            model_name='georamauser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identifier of the user.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identifier of the membership.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Organisation associated with the membership.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.organisation'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(help_text='User associated with the membership.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='domain',
            field=models.CharField(help_text='Domain used to identify the organisation.', unique=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identifier of the organisation.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(help_text='Name of the organisation.'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='public_access',
            field=models.BooleanField(default=False, help_text='Whether anonymous users can access this organisation.'),
        ),
    ]
