# Generated by Django 6.0.6 on 2026-07-07 12:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('integration', '0002_alter_datasource_styles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identifier of the metadata.', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('license', models.TextField(default='\n    This dataset is made available under the Open Database\n    License: http://opendatacommons.org/licenses/odbl/1.0/.\n    Any rights in individual contents of the database are licensed\n    under the Database Contents\n    License: http://opendatacommons.org/licenses/dbcl/1.0/\n    ')),
                ('fees', models.TextField(default='No fees apply.')),
                ('access_constraints', models.TextField(default='No access constraints apply.')),
            ],
            options={
                'verbose_name': 'metadata',
                'verbose_name_plural': 'metadata',
            },
        ),
        migrations.CreateModel(
            name='WmsLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identifier of the wms layer.', primary_key=True, serialize=False)),
                ('extent_buffer', models.FloatField(default=0.0)),
                ('queryable', models.BooleanField(blank=True, default=True, null=True)),
                ('extent', models.CharField(blank=True, max_length=1000, null=True)),
                ('extent_wgs84', models.CharField(blank=True, max_length=1000, null=True)),
                ('preview', models.BinaryField(blank=True, null=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wms_layers', related_query_name='wms_layers', to='integration.datasource')),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wms_layer', to='maps.metadata')),
            ],
            options={
                'verbose_name': 'wms layer',
                'verbose_name_plural': 'wms layers',
            },
        ),
        migrations.CreateModel(
            name='WmsLayerGroupObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_object_permissions', to='maps.wmslayer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'abstract': False,
                'unique_together': {('group', 'permission', 'content_object')},
            },
        ),
        migrations.CreateModel(
            name='WmsLayerUserObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='maps.wmslayer')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'permission', 'content_object')},
            },
        ),
    ]
