# Generated by Django 5.0.6 on 2025-06-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedaswms",
            name="queryable",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
