# Generated by Django 5.0.6 on 2025-06-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0002_publishedaswms_queryable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publishedaswms",
            options={"verbose_name": "WMS Layer", "verbose_name_plural": "WMS Layers"},
        ),
        migrations.AlterField(
            model_name="publishedaswms",
            name="queryable",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
