# Generated by Django 5.0.6 on 2025-08-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0003_alter_publishedaswms_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedaswms",
            name="extent",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="publishedaswms",
            name="preview",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
