# Generated by Django 5.0.6 on 2025-08-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0004_publishedaswms_extent_publishedaswms_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedaswms",
            name="extent_wgs84",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
