# Generated by Django 5.0.6 on 2025-08-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0004_publishedaswms_extent_publishedaswms_preview"),
        ("maps", "0005_publishedaswms_extent_wgs84"),
    ]

    operations = []
