# Generated by Django 5.2.10 on 2026-02-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0006_merge_20250815_1507"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publishedaswms",
            options={
                "permissions": [
                    ("can_manage_object_permissions", "Can manage object permissions")
                ],
                "verbose_name": "WMS Layer",
                "verbose_name_plural": "WMS Layers",
            },
        ),
    ]
