# Generated by Django 5.0.6 on 2024-07-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_integration", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("name", "version")},
        ),
    ]
