# Generated by Django 5.0.6 on 2024-08-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_integration", "0007_alter_project_unique_together_project_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=1000),
        ),
    ]
