# Generated by Django 5.0.6 on 2024-08-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_integration", "0011_rasterdataset_crs_vectordataset_crs"),
    ]

    operations = [
        migrations.AddField(
            model_name="rasterdataset",
            name="bbox_wgs84",
            field=models.CharField(default="0,0,0,0", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vectordataset",
            name="bbox_wgs84",
            field=models.CharField(default="0,0,0,0", max_length=1000),
            preserve_default=False,
        ),
    ]
