# Generated by Django 5.0.6 on 2024-09-18 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_integration", "0013_customdataset"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mandant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="project",
            name="mandant",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mandants",
                related_query_name="mandant",
                to="data_integration.mandant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("name", "version", "mandant")},
        ),
        migrations.RemoveField(
            model_name="project",
            name="group",
        ),
    ]
