# Generated by Django 5.0.6 on 2024-09-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_integration", "0016_mandant_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="customdataset",
            name="remote",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rasterdataset",
            name="remote",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vectordataset",
            name="remote",
            field=models.BooleanField(default=False),
        ),
    ]
