# Generated by Django 5.0.6 on 2024-10-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_integration", "0017_customdataset_remote_rasterdataset_remote_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customdataset",
            name="remote",
        ),
        migrations.RemoveField(
            model_name="rasterdataset",
            name="remote",
        ),
        migrations.RemoveField(
            model_name="vectordataset",
            name="remote",
        ),
    ]
