# Generated by Django 5.0.6 on 2024-12-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_integration", "0018_remove_customdataset_remote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vectordataset",
            name="extent_buffer",
            field=models.FloatField(default=0.0),
        ),
    ]
