# Generated by Django 5.0.6 on 2024-12-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_integration", "0019_vectordataset_extent_buffer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vectordataset",
            name="extent_buffer",
        ),
    ]
