# Generated by Django 5.0.6 on 2025-01-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_integration", "0020_remove_vectordataset_extent_buffer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customdataset",
            name="maximum_scale",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="customdataset",
            name="minimum_scale",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="rasterdataset",
            name="maximum_scale",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="rasterdataset",
            name="minimum_scale",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="vectordataset",
            name="maximum_scale",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="vectordataset",
            name="minimum_scale",
            field=models.FloatField(null=True),
        ),
    ]
