# Generated by Django 5.0.6 on 2025-04-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_integration", "0022_alter_customdataset_qgis_layer_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customdataset",
            name="style",
        ),
        migrations.RemoveField(
            model_name="rasterdataset",
            name="style",
        ),
        migrations.RemoveField(
            model_name="vectordataset",
            name="style",
        ),
        migrations.AddField(
            model_name="customdataset",
            name="styles",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="rasterdataset",
            name="styles",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="vectordataset",
            name="styles",
            field=models.JSONField(default=dict),
        ),
    ]
