# Generated by Django 5.0.6 on 2025-04-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_integration", "0023_remove_customdataset_style_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="alias",
            field=models.CharField(default="UNSET", max_length=1000),
        ),
        migrations.AddField(
            model_name="field",
            name="nullable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="field",
            name="simple_type",
            field=models.CharField(default="UNSET", max_length=1000),
        ),
    ]
