# Generated by Django 5.0.6 on 2025-04-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_integration", "0024_field_alias_field_nullable_field_simple_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="field",
            old_name="simple_type",
            new_name="type_simple",
        ),
    ]
