# Generated by Django 5.0.6 on 2025-04-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_integration", "0025_rename_simple_type_field_type_simple"),
    ]

    operations = [
        migrations.AddField(
            model_name="vectordataset",
            name="geometry_type_simple",
            field=models.CharField(default="UNSET", max_length=1000),
        ),
        migrations.AddField(
            model_name="vectordataset",
            name="geometry_type_wkb",
            field=models.CharField(default="UNSET", max_length=1000),
        ),
    ]
