# Generated by Django 5.0.6 on 2025-07-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_integration", "0026_vectordataset_geometry_type_simple_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="field",
            old_name="type_simple",
            new_name="type_oapif",
        ),
        migrations.AddField(
            model_name="field",
            name="is_primary_key",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="field",
            name="length",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="field",
            name="precision",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="field",
            name="type_oapif_format",
            field=models.CharField(default="UNSET", max_length=1000),
        ),
        migrations.AddField(
            model_name="field",
            name="type_wfs",
            field=models.CharField(default="UNSET", max_length=1000),
        ),
    ]
