# Generated by Django 5.0.6 on 2025-07-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_integration", "0027_rename_type_simple_field_type_oapif_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="type_oapif_format",
            field=models.CharField(default="UNSET", max_length=1000, null=True),
        ),
    ]
