# Generated by Django 5.0.6 on 2025-07-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_integration', '0028_alter_field_type_oapif_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='comment',
            field=models.CharField(default='UNSET', max_length=1000),
        ),
    ]
