# Generated by Django 5.2.10 on 2026-01-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_integration", "0029_field_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=1000, verbose_name="name"),
        ),
    ]
