# Generated by Django 5.2.10 on 2026-03-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_integration", "0031_add_app_permission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customdataset",
            options={
                "verbose_name": "Custom Dataset",
                "verbose_name_plural": "Custom Datasets",
            },
        ),
        migrations.AlterModelOptions(
            name="field",
            options={
                "verbose_name": "Vector Dataset Field",
                "verbose_name_plural": "Vector Dataset Fields",
            },
        ),
        migrations.AlterModelOptions(
            name="mandant",
            options={"verbose_name": "Mandant", "verbose_name_plural": "Mandants"},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "Project", "verbose_name_plural": "Projects"},
        ),
        migrations.AlterModelOptions(
            name="rasterdataset",
            options={
                "verbose_name": "Raster Dataset",
                "verbose_name_plural": "Raster Datasets",
            },
        ),
        migrations.AlterModelOptions(
            name="vectordataset",
            options={
                "verbose_name": "Vector Dataset",
                "verbose_name_plural": "Vector Datasets",
            },
        ),
    ]
