# Generated by Django 5.2.16 on 2026-09-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_integration', '0033_remove_path_field_from_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdataset',
            name='is_wms_background',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rasterdataset',
            name='is_wms_background',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vectordataset',
            name='is_wms_background',
            field=models.BooleanField(default=False),
        ),
    ]
