# Generated by Django 5.0.6 on 2024-07-10 14:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedAsOgcApiFeatures',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public', models.BooleanField(default=True)),
                ('project', models.CharField(max_length=1000, unique=True)),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('license', models.TextField(default='\n    This dataset is made available under the Open Database\n    License: http://opendatacommons.org/licenses/odbl/1.0/.\n    Any rights in individual contents of the database are licensed\n    under the Database Contents\n    License: http://opendatacommons.org/licenses/dbcl/1.0/\n    ')),
                ('fees', models.TextField(default='No fees apply.')),
                ('access_constraints', models.TextField(default='No access constraints apply.')),
                ('srs', models.JSONField(default=list)),
                ('column_permission', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishedAsWfs',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public', models.BooleanField(default=True)),
                ('project', models.CharField(max_length=1000, unique=True)),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('license', models.TextField(default='\n    This dataset is made available under the Open Database\n    License: http://opendatacommons.org/licenses/odbl/1.0/.\n    Any rights in individual contents of the database are licensed\n    under the Database Contents\n    License: http://opendatacommons.org/licenses/dbcl/1.0/\n    ')),
                ('fees', models.TextField(default='No fees apply.')),
                ('access_constraints', models.TextField(default='No access constraints apply.')),
                ('srs', models.JSONField(default=list)),
                ('column_permission', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ColumnOgcApiFeatures',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('data_type', models.CharField(choices=[('numeric', 'Numerical Type'), ('string', 'Alphanumerical Type'), ('boolean', 'Boolean Type'), ('date', 'Date Type'), ('datetime', 'Datetime Type')], max_length=1000)),
                ('published_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', related_query_name='column', to='vectorparrot.publishedasogcapifeatures')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ColumnWfs',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('data_type', models.CharField(choices=[('numeric', 'Numerical Type'), ('string', 'Alphanumerical Type'), ('boolean', 'Boolean Type'), ('date', 'Date Type'), ('datetime', 'Datetime Type')], max_length=1000)),
                ('published_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', related_query_name='column', to='vectorparrot.publishedaswfs')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
