# Generated by Django 5.0.6 on 2024-08-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorparrot', '0002_publishedasogcapifeatures_dataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedasogcapifeatures',
            name='name',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='publishedasogcapifeatures',
            name='project',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='publishedaswfs',
            name='name',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='publishedaswfs',
            name='project',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
    ]
