# Generated by Django 5.0.6 on 2024-08-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorparrot', '0004_alter_publishedasogcapifeatures_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedasogcapifeatures',
            name='project',
        ),
        migrations.RemoveField(
            model_name='publishedasogcapifeatures',
            name='srs',
        ),
        migrations.RemoveField(
            model_name='publishedaswfs',
            name='project',
        ),
        migrations.RemoveField(
            model_name='publishedaswfs',
            name='srs',
        ),
        migrations.AlterField(
            model_name='publishedasogcapifeatures',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='publishedasogcapifeatures',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='publishedaswfs',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='publishedaswfs',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
