# Generated by Django 5.0.6 on 2024-08-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorparrot', '0005_remove_publishedasogcapifeatures_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedasogcapifeatures',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publishedasogcapifeatures',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='publishedasogcapifeatures',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='publishedaswfs',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publishedaswfs',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='publishedaswfs',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
