# Generated by Django 5.0.6 on 2024-08-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorparrot', '0006_alter_publishedasogcapifeatures_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnogcapifeatures',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='columnwfs',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publishedasogcapifeatures',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publishedaswfs',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
