# Generated by Django 5.0.6 on 2024-08-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorparrot', '0007_alter_columnogcapifeatures_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnogcapifeatures',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='columnwfs',
            name='data_type',
        ),
        migrations.AlterField(
            model_name='columnogcapifeatures',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='columnwfs',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
