# Generated by Django 5.0.6 on 2024-09-16 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clogs', '0001_initial'),
        ('qmeleon', '0013_customdataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublishedaslayerwms',
            name='child_layers',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='historicalpublishedaslayerwms',
            name='max_resolution_hint',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='historicalpublishedaslayerwms',
            name='min_resolution_hint',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='publishedaslayerwms',
            name='child_layers',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='publishedaslayerwms',
            name='max_resolution_hint',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='publishedaslayerwms',
            name='min_resolution_hint',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='publishedaslayerwms',
            name='dataset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='published_as_geogirafe_wmss', related_query_name='published_as_geogirafe_wms', to='qmeleon.rasterdataset'),
        ),
        migrations.AlterField(
            model_name='publishedaslayerwms',
            name='layer_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wms_datasets', related_query_name='wms_dataset', to='clogs.layergroupmp'),
        ),
        migrations.AlterField(
            model_name='publishedaslayerwmts',
            name='layer_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wmts_datasets', related_query_name='wmts_dataset', to='clogs.layergroupmp'),
        ),
    ]
