# Generated by Django 5.0.6 on 2024-09-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clogs', '0002_historicalpublishedaslayerwms_child_layers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublishedaslayerwms',
            name='dimensions',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='historicalpublishedaslayerwmts',
            name='dimensions',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='layergroupmp',
            name='dimensions',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='layergroupmp',
            name='metadata',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='layergroupmp',
            name='mixed',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='layergroupmp',
            name='ogc_server',
            field=models.CharField(default=None, max_length=2048),
        ),
        migrations.AddField(
            model_name='publishedaslayerwms',
            name='dimensions',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='publishedaslayerwmts',
            name='dimensions',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='historicalpublishedaslayerwms',
            name='metadata',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='historicalpublishedaslayerwmts',
            name='metadata',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='publishedaslayerwms',
            name='metadata',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='publishedaslayerwmts',
            name='metadata',
            field=models.JSONField(default=None),
        ),
    ]
