# Generated by Django 5.0.6 on 2024-09-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clogs', '0003_historicalpublishedaslayerwms_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layergroupmp',
            name='dimensions',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='layergroupmp',
            name='metadata',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='layergroupmp',
            name='mixed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='layergroupmp',
            name='ogc_server',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
    ]
