# Generated by Django 5.0.6 on 2024-09-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clogs', '0004_alter_layergroupmp_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpublishedaslayerwms',
            name='dimensions',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpublishedaslayerwms',
            name='metadata',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpublishedaslayerwmts',
            name='dimensions',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpublishedaslayerwmts',
            name='metadata',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publishedaslayerwms',
            name='dimensions',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publishedaslayerwms',
            name='metadata',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publishedaslayerwmts',
            name='dimensions',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publishedaslayerwmts',
            name='metadata',
            field=models.JSONField(default=None, null=True),
        ),
    ]
