# Generated by Django 5.0.6 on 2024-09-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clogs', '0005_alter_historicalpublishedaslayerwms_dimensions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalogcserver',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='ogcserver',
            name='auth',
        ),
        migrations.AddField(
            model_name='historicalogcserver',
            name='credential',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpublishedaslayerwms',
            name='themes_json_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalpublishedaslayerwmts',
            name='themes_json_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalpublishedastheme',
            name='themes_json_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='layergroupmp',
            name='themes_json_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ogcserver',
            name='credential',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publishedaslayerwms',
            name='themes_json_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publishedaslayerwmts',
            name='themes_json_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publishedastheme',
            name='themes_json_id',
            field=models.IntegerField(null=True),
        ),
    ]
