# Generated by Django 5.0.6 on 2024-09-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clogs', '0006_remove_historicalogcserver_auth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalogcserver',
            name='name',
            field=models.CharField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalogcserver',
            name='namespace',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='ogcserver',
            name='name',
            field=models.CharField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ogcserver',
            name='namespace',
            field=models.CharField(null=True),
        ),
    ]
