# Generated by Django 5.0.6 on 2024-09-17 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clogs', '0007_alter_historicalogcserver_name_and_more'),
        ('qmeleon', '0013_customdataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalogcserver',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='ogc_server', to='qmeleon.project'),
        ),
        migrations.AddField(
            model_name='historicalpublishedaslayerwms',
            name='ogc_server',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='ogcserver',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ogc_servers', related_query_name='ogc_server', to='qmeleon.project'),
        ),
        migrations.AddField(
            model_name='publishedaslayerwms',
            name='ogc_server',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalogcserver',
            name='name',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='ogcserver',
            name='name',
            field=models.CharField(null=True),
        ),
    ]
