# Generated by Django 5.0.6 on 2024-09-18 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clogs', '0008_historicalogcserver_project_and_more'),
        ('qmeleon', '0016_mandant_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalogcserver',
            name='project',
        ),
        migrations.RemoveField(
            model_name='ogcserver',
            name='project',
        ),
        migrations.AddField(
            model_name='historicalogcserver',
            name='mandant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='ogc_server', to='qmeleon.mandant'),
        ),
        migrations.AddField(
            model_name='ogcserver',
            name='mandant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ogc_servers', related_query_name='ogc_server', to='qmeleon.mandant'),
        ),
    ]
