site_name: 'Georama'
site_url: 'https://opengisch.github.io/georama'
site_description: 'Georama Documentation Pages.'
site_author: 'Clemens Rudert'

repo_url: 'https://github.com/opengisch/georama/'
repo_name: 'opengisch/georama'
edit_uri: docs/
docs_dir: src
nav:
  - "Welcome": index.md
  - "Quick Start": quick_start.md
  - "Setup Environment Variables": setup_env.md
  - "DEV Setup":
      - "General": dev/general.md
      - "Local 💻": dev/local.md
      - "Local with QSL 💻": dev/local_and_qsl.md
      - "Docker 🐳": dev/docker.md
      - "Docker Compose 🐳": dev/docker_compose.md
  - "Workflow": workflow.md
  - "General Hints": general_hints.md
  - "Process": process.md
  - "Auth": dev_guides/auth.md
  - API References:
    - Overview: api_references/overview.md
    - Core: api_references/core.md
    - Data integration: api_references/data_integration.md
    - Maps: api_references/maps.md
    - Features: api_references/features.md
    - WebGIS: api_references/webgis.md
  - Endpoints: endpoints.md
  - WebGIS: webgis.md
  - Topics:
    - "Docker": build-process_DAG.md
    - "CI/CD": cicd.md
  - tags: tags.md
theme:
  # 1
  name: material
  icon:
    logo: material/palette
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    default: material/tag
    favicon: assets/logo/favicon.ico

  features:
    - navigation.path
    - navigation.top
    - navigation.footer

plugins:
  # Enable jinja inside your markdown files
  # https://github.com/fralau/mkdocs_macros_plugin
  - macros
  # Authors need installation
  # - git-authors
  - tags:
      tags_file: tags.md
  # BASIC SEARCH PLUGIN
  - search
  - autorefs
  # MERMAID Render Support
  - mermaid2
  # Directives Provider for docstrings parsing
  - mkdocstrings:
      handlers:
        python:
          paths: [ ../src ]
          options:
            filters:
              exclude:
                # this speeds up doc generation substantially
                - "georama.maps.interfaces"
            show_submodules: true
            show_if_no_docstring: true
  # gain the ability to tap-in to the build process
  - gen-files:
      # scripts allowing to programmatically generate .md content
      scripts:
        # custom script to generate API references
        - scripts/gen_api_refs_pages.py
  # programmatically generate Nav Item: ie 'reference/' entry in Navigation
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

markdown_extensions:
  - mkdocs-click
  - pymdownx.highlight
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


extra:
  generator: false
  favicon: assets/logo/favicon.ico
