name: Build Docker Images

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize, closed]

jobs:
  docker-image-latest-dev:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build release
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          target: dev
          cache-from: type=local,src=cache
          tags: ghcr.io/${{ github.repository }}:latest-dev

  ghcr-pr-image:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push PR Image
        if: github.event.action != 'closed'
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.head_ref }}

      - name: Delete PR Image
        if: github.event.action == 'closed'
        run: |
          echo "Deleting GHCR image for PR branch ${{ github.head_ref }}"
          # Löschen über GitHub API
          curl -s -X DELETE \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://ghcr.io/v2/${{ github.repository }}/manifests/${{ github.head_ref }} || true
