name: MissingDjangoMigrations
on:
  push:
    branches:
      - "*"
    tags:
      - v*
jobs:
  test-migrations:
    name: Test no migrations were left behind
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v6
      - name: Prepare Build Environment
        run: |
          cp .env.dev .env
          echo "UID=$(id -u)" >> .env
          echo "GID=$(id -g)" >> .env
          echo "QSL_SOURCE_BRANCH=master" >> .env
          cat .env
      - name: Build Georama Image
        run: |
          docker compose build georama
      - name: Start Docker composition
        run: |
          docker compose up -d
      - name: Check migrations
        env:
          DJANGO_CONFIGURATION: Dev
        run: uv run manage makemigrations --check --dry-run
