name: CI/CD Pipeline
on:
  push:
    branches:
      - "*"
    tags:
      - v*

jobs:

  gitattributes:
    name: Check style (git-attributes)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: sudo rm /etc/apt/sources.list.d/*.list
      - name: Run make git-attributes
        run: make git-attributes

  # TODO: Add linting here when we decided what approach we go for.

  test-py:
    name: Test Python
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python v${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: sudo rm /etc/apt/sources.list.d/*.list
      - run: sudo apt update
      - run: sudo apt-get install  -y  libpq-dev python3-gdal python3-numpy python3-venv git make
      - name: Start services
        run: |
          cp .env.ci .env
          docker compose -f "docker-compose.yml" up georama-db -d
      - name: Set up test environment
        run: make install-test
      - name: Run tests for Python ${{ matrix.python-version }} on ${{ matrix.platform }}
        run: make tests
      - name: Rename Coverage Files
        shell: bash
        run: |
          cp .coverage.final_combined.xml coverage-${{ matrix.platform }}-${{ matrix.python-version }}.final_combined.xml
      - name: Stop services
        if: always()
        run: docker compose -f "docker-compose.yml" down
# TODO: Uncomment this once we have decided if we use codecov?
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v5
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          env_vars: OS,PYTHON
#          fail_ci_if_error: true
#          files: coverage-${{ matrix.platform }}-${{ matrix.python-version }}.final_combined.xml
#          flags: unittests
#          name: codecov-unittest
#          verbose: true
